//! An installed copy of the document's font, supplied as bytes the way the app
//! process supplies them. Every font here is original and generated by
//! `testdata/make_installed_fonts.py`, which also says what each one is for;
//! nothing depends on what the machine running the tests has installed, except
//! the two platform-gated checks at the end.
use super::*;
use crate::textedit::{preview_layout, scan, tests::with_content, write, Change, EditFont, Layout};
use lopdf::{dictionary, Dictionary, Document, Object, Stream};

const NAME: &str = "TPDFInstalledSans";
const FULL: &[u8] = include_bytes!("full.ttf");
const SUBSET: &[u8] = include_bytes!("subset.ttf");
const SPARSE: &[u8] = include_bytes!("sparse.ttf");
const COLLECTION: &[u8] = include_bytes!("collection.ttc");
const CFF: &[u8] = include_bytes!("cff.otf");
const COLOUR: &[u8] = include_bytes!("colour.ttf");
const SUBSET_CFF: &[u8] = include_bytes!("subset.cff");
const CFF_2048: &[u8] = include_bytes!("cff2048.otf");
/// What the preview says when the installed copy is used.
const USED: &str = "TPDF Installed Sans (installed)";

/// A page whose two runs are set in the document's subset of the font, as a
/// producer embeds one: a WinAnsi TrueType font with the subset tag on its
/// name and each width its program's advance.
fn document() -> Document {
    document_with(SUBSET)
}

fn document_with(program: &[u8]) -> Document {
    let mut doc = with_content(b"BT /F1 12 Tf 40 180 Td (TITLE) Tj 0 -80 Td (SECOND) Tj ET");
    let face = Face::parse(program, 0).unwrap();
    let unit = 1000. / f64::from(face.units_per_em());
    let widths = (32_u8..=84)
        .map(|code| {
            let width = face
                .glyph_index(char::from(code))
                .and_then(|id| face.glyph_hor_advance(id))
                .map_or(0., |advance| f64::from(advance) * unit);
            Object::Real(width as f32)
        })
        .collect::<Vec<_>>();
    let stream = doc.add_object(Stream::new(
        dictionary! { "Length1" => program.len() as i64 },
        program.to_vec(),
    ));
    let tagged = format!("ABCDEF+{NAME}");
    let descriptor = doc.add_object(dictionary! {
        "Type" => "FontDescriptor", "FontName" => tagged.as_str(), "Flags" => 32,
        "FontBBox" => vec![0.into(), 0.into(), 1000.into(), 700.into()],
        "ItalicAngle" => 0, "Ascent" => 879, "Descent" => -195,
        "CapHeight" => 700, "StemV" => 80, "FontFile2" => stream
    });
    let font = doc.add_object(dictionary! {
        "Type" => "Font", "Subtype" => "TrueType", "BaseFont" => tagged.as_str(),
        "Encoding" => "WinAnsiEncoding", "FirstChar" => 32, "LastChar" => 84,
        "Widths" => widths, "FontDescriptor" => descriptor
    });
    for page in crate::pagetree::ordered_pages(&doc) {
        doc.get_dictionary_mut(page).unwrap().set(
            "Resources",
            dictionary! { "Font" => dictionary! { "F1" => font } },
        );
    }
    doc
}

fn supplied(program: &[u8], index: Option<u32>) -> Installed {
    Installed {
        name: NAME.into(),
        index,
        program: program.to_vec(),
    }
}

fn edit(doc: &Document, replacement: &str, font: EditFont, installed: Option<Installed>) -> Change {
    let page = scan(doc, 0).unwrap();
    Change {
        page: 0,
        revision: page.revision,
        operator: page.runs[0].operator,
        original: page.runs[0].text.clone(),
        replacement: replacement.into(),
        layout: Some(Layout {
            width: 250.,
            height: 20.,
            size: 12.,
            wrap: false,
            font,
            grow: false,
            installed,
        }),
    }
}

/// The byte offset of a table in a single-font program.
fn table(program: &[u8], tag: &[u8; 4]) -> usize {
    let count = u16::from_be_bytes([program[4], program[5]]) as usize;
    program[12..12 + 16 * count]
        .chunks_exact(16)
        .find(|record| &record[..4] == tag)
        .map(|record| u32::from_be_bytes(record[8..12].try_into().unwrap()) as usize)
        .expect("table")
}

/// `FULL` with another OS/2 `fsType`.
fn with_rights(rights: u16) -> Vec<u8> {
    let mut program = FULL.to_vec();
    let at = table(&program, b"OS/2") + 8;
    program[at..at + 2].copy_from_slice(&rights.to_be_bytes());
    program
}

/// `FULL` with `ch`'s advance moved by `units` font units.
fn with_advance(ch: char, units: i16) -> Vec<u8> {
    let face = Face::parse(FULL, 0).unwrap();
    let id = face.glyph_index(ch).unwrap();
    let advance = face.glyph_hor_advance(id).unwrap();
    let mut program = FULL.to_vec();
    let at = table(&program, b"hmtx") + 4 * usize::from(id.0);
    program[at..at + 2].copy_from_slice(&advance.wrapping_add_signed(units).to_be_bytes());
    program
}

/// The font resource a written edit added, and the program it embeds.
fn embedded(doc: &Document) -> (Dictionary, Dictionary, Vec<u8>) {
    let page = crate::pagetree::ordered_pages(doc)[0];
    let resources = doc.get_dictionary(page).unwrap().get(b"Resources").unwrap();
    let fonts = resources
        .as_dict()
        .unwrap()
        .get(b"Font")
        .unwrap()
        .as_dict()
        .unwrap();
    let (_, font) = fonts
        .iter()
        .find(|(name, _)| name.starts_with(b"TPDFEdit"))
        .expect("an added font");
    let font = doc
        .get_dictionary(font.as_reference().unwrap())
        .unwrap()
        .clone();
    embedded_font(doc, &font)
}

/// A Type0 font's descendant, and the program it embeds.
fn embedded_font(doc: &Document, font: &Dictionary) -> (Dictionary, Dictionary, Vec<u8>) {
    let font = font.clone();
    let child = font.get(b"DescendantFonts").unwrap().as_array().unwrap()[0]
        .as_reference()
        .unwrap();
    let child = doc.get_dictionary(child).unwrap().clone();
    let descriptor = doc
        .get_dictionary(
            child
                .get(b"FontDescriptor")
                .unwrap()
                .as_reference()
                .unwrap(),
        )
        .unwrap();
    let program = doc
        .get_object(
            descriptor
                .get(b"FontFile2")
                .or_else(|_| descriptor.get(b"FontFile3"))
                .unwrap()
                .as_reference()
                .unwrap(),
        )
        .unwrap()
        .as_stream()
        .unwrap()
        .content
        .clone();
    (font, child, program)
}

#[test]
fn an_installed_copy_sets_the_characters_its_subset_lacks() {
    let doc = document();
    // Without the file, automatic mode names what it wants and uses Noto.
    let asked = preview_layout(&doc, &edit(&doc, "TITLE Ab", EditFont::Auto, None)).unwrap();
    assert_eq!(asked.font, "Noto Sans");
    assert_eq!(asked.wants.as_deref(), Some(NAME));
    assert!(asked.installed.is_none());
    // With it, the installed copy, and the subset the journal keeps.
    let change = edit(&doc, "TITLE Ab", EditFont::Auto, Some(supplied(FULL, None)));
    let report = preview_layout(&doc, &change).unwrap();
    assert_eq!(report.font, USED);
    assert_eq!(report.wants, None);
    let kept = report.installed.expect("the subset the journal keeps");
    assert_eq!(kept.name, NAME);
    let face = Face::parse(&kept.program, 0).unwrap();
    let whole = Face::parse(FULL, 0).unwrap();
    // "TITLE SECOND" and "Ab", .notdef and the space: a subset, not the file.
    assert_eq!(face.number_of_glyphs(), 13);
    assert!(face.number_of_glyphs() < whole.number_of_glyphs());
    assert!(carries_name(&face, NAME));
    assert!(face.raw_face().table(Tag::from_bytes(b"OS/2")).is_some());
    for ch in "TITLE SECONDAb".chars() {
        let id = face.glyph_index(ch).unwrap();
        assert_eq!(
            face.glyph_hor_advance(id),
            whole.glyph_hor_advance(whole.glyph_index(ch).unwrap()),
            "{ch}"
        );
    }
    // The journal's subset is itself an installed copy, and sets the same text.
    let journal = edit(&doc, "TITLE Ab", EditFont::Auto, Some(kept.clone()));
    let again = preview_layout(&doc, &journal).unwrap();
    assert_eq!(again.font, USED);
    assert_eq!(again.installed.as_ref(), Some(&kept));

    let mut saved = doc.clone();
    write(&mut saved, std::slice::from_ref(&journal)).unwrap();
    let (font, child, program) = embedded(&saved);
    assert_eq!(program, kept.program, "the subset is what is embedded");
    let base = font.get(b"BaseFont").unwrap().as_name().unwrap();
    assert!(base.ends_with(format!("+{NAME}").as_bytes()) && base.len() == NAME.len() + 7);
    // Every width the descendant declares is the installed advance of the
    // character its ToUnicode entry names, one code per distinct character.
    let map = saved
        .get_object(font.get(b"ToUnicode").unwrap().as_reference().unwrap())
        .unwrap()
        .as_stream()
        .unwrap()
        .content
        .clone();
    let map = String::from_utf8(map).unwrap();
    let widths = child.get(b"W").unwrap().as_array().unwrap();
    assert_eq!(widths.len(), 2 * "TILE Ab".len());
    for pair in widths.chunks_exact(2) {
        let code = pair[0].as_i64().unwrap();
        let width = f64::from(pair[1].as_array().unwrap()[0].as_float().unwrap());
        let entry = format!("<{code:04X}> <");
        let at = map.find(&entry).expect("a ToUnicode entry") + entry.len();
        let unit = u32::from_str_radix(&map[at..at + 4], 16).unwrap();
        let ch = char::from_u32(unit).unwrap();
        let id = whole.glyph_index(ch).unwrap();
        let advance = f64::from(whole.glyph_hor_advance(id).unwrap()) * 1000. / 2048.;
        assert!(
            (advance - width).abs() < 1e-3,
            "{ch}: {width} against {advance}"
        );
    }

    // Saved, reopened, read back, and edited again with characters that were
    // in neither subset.
    let mut bytes = Vec::new();
    saved.save_to(&mut bytes).unwrap();
    let mut reopened = Document::load_mem(&bytes).unwrap();
    assert_eq!(scan(&reopened, 0).unwrap().runs[0].text, "TITLE Ab");
    let next = edit(&reopened, "TITLE Abz", EditFont::Auto, None);
    assert_eq!(
        preview_layout(&reopened, &next).unwrap().wants.as_deref(),
        Some(NAME),
        "the reopened subset is the same font by name"
    );
    let next = edit(
        &reopened,
        "TITLE Abz",
        EditFont::Auto,
        Some(supplied(FULL, None)),
    );
    assert_eq!(preview_layout(&reopened, &next).unwrap().font, USED);
    write(&mut reopened, &[next]).unwrap();
    assert_eq!(scan(&reopened, 0).unwrap().runs[0].text, "TITLE Abz");
}

#[test]
fn the_documents_own_subset_is_still_preferred_when_it_covers_the_text() {
    let doc = document();
    let change = edit(&doc, "TILE", EditFont::Auto, Some(supplied(FULL, None)));
    let report = preview_layout(&doc, &change).unwrap();
    assert_eq!(report.font, format!("ABCDEF+{NAME}"));
    assert_eq!((report.wants, report.installed), (None, None));
}

#[test]
fn only_automatic_mode_uses_an_installed_copy() {
    let doc = document();
    let chosen = edit(
        &doc,
        "TITLE Ab",
        EditFont::NotoSans,
        Some(supplied(FULL, None)),
    );
    let report = preview_layout(&doc, &chosen).unwrap();
    assert_eq!(report.font, "Noto Sans");
    assert_eq!((report.wants, report.installed), (None, None));
    let original = edit(
        &doc,
        "TITLE Ab",
        EditFont::Original,
        Some(supplied(FULL, None)),
    );
    assert!(preview_layout(&doc, &original).is_err());
}

#[test]
fn a_width_that_disagrees_falls_to_noto_and_says_why() {
    let doc = document();
    let differs = format!("Noto Sans (the installed {NAME} differs from the document's copy)");
    // Two units at 2048 per em are 0.98 thousandths: the same font. Three are
    // 1.46: not. `T` is in the document's subset and not in the replacement's
    // new characters, so only the width check can see it.
    for (units, expected) in [
        (2, USED),
        (-2, USED),
        (3, differs.as_str()),
        (-3, &differs),
        (200, &differs),
    ] {
        let program = with_advance('T', units);
        let change = edit(
            &doc,
            "TITLE Ab",
            EditFont::Auto,
            Some(supplied(&program, None)),
        );
        let report = preview_layout(&doc, &change).unwrap();
        assert_eq!(report.font, expected, "{units} units");
        assert_eq!(report.installed.is_some(), expected == USED);
    }
    // A copy without a character the document's subset has is not its font.
    let change = edit(
        &doc,
        "TITLE Ab",
        EditFont::Auto,
        Some(supplied(SPARSE, None)),
    );
    assert_eq!(preview_layout(&doc, &change).unwrap().font, differs);
}

#[test]
fn rights_that_forbid_editing_or_subsetting_refuse_the_installed_copy() {
    let doc = document();
    let refused = format!("Noto Sans (the installed {NAME} does not permit editing)");
    for (rights, expected) in [
        (0_u16, USED),
        (0x8, USED),
        (0x2, refused.as_str()),
        (0x4, &refused),
        (0x100, &refused),
        (0x200, &refused),
        (0x108, &refused),
    ] {
        let program = with_rights(rights);
        let change = edit(
            &doc,
            "TITLE Ab",
            EditFont::Auto,
            Some(supplied(&program, None)),
        );
        assert_eq!(
            preview_layout(&doc, &change).unwrap().font,
            expected,
            "fsType {rights:#x}"
        );
    }
}

#[test]
fn a_collection_face_must_carry_the_name_the_document_asks_for() {
    let doc = document();
    let unreadable = format!("Noto Sans (the installed {NAME} could not be read)");
    for (index, expected) in [
        (Some(1), USED),
        // CoreText names the file and not the face.
        (None, USED),
        // Face 0 is another font; the name table is the last word, not the index.
        (Some(0), unreadable.as_str()),
        (Some(2), &unreadable),
    ] {
        let change = edit(
            &doc,
            "TITLE Ab",
            EditFont::Auto,
            Some(supplied(COLLECTION, index)),
        );
        assert_eq!(
            preview_layout(&doc, &change).unwrap().font,
            expected,
            "{index:?}"
        );
    }
    // A single font is face 0, whatever else is claimed.
    let change = edit(
        &doc,
        "TITLE Ab",
        EditFont::Auto,
        Some(supplied(FULL, Some(1))),
    );
    assert_eq!(preview_layout(&doc, &change).unwrap().font, unreadable);
    // A font of another name, even supplied under this one.
    let mut other = supplied(COLLECTION, Some(0));
    other.program = {
        let face = Face::parse(COLLECTION, 0).unwrap();
        assert!(!carries_name(&face, NAME));
        COLLECTION.to_vec()
    };
    let change = edit(&doc, "TITLE Ab", EditFont::Auto, Some(other));
    assert_eq!(preview_layout(&doc, &change).unwrap().font, unreadable);
}

#[test]
fn a_supplied_name_that_is_not_the_documents_is_not_used() {
    let doc = document();
    let mut wrong = supplied(FULL, None);
    wrong.name = "TPDFOtherSans".into();
    let change = edit(&doc, "TITLE Ab", EditFont::Auto, Some(wrong));
    let report = preview_layout(&doc, &change).unwrap();
    assert_eq!(
        report.font,
        format!("Noto Sans (the installed {NAME} could not be read)")
    );
    assert!(report.installed.is_none());
}

#[test]
fn an_installed_file_past_the_bound_is_refused() {
    let doc = document();
    let mut program = FULL.to_vec();
    program.resize(MAX_BYTES, 0);
    let change = edit(
        &doc,
        "TITLE Ab",
        EditFont::Auto,
        Some(supplied(&program, None)),
    );
    assert_eq!(preview_layout(&doc, &change).unwrap().font, USED);
    program.push(0);
    let change = edit(
        &doc,
        "TITLE Ab",
        EditFont::Auto,
        Some(supplied(&program, None)),
    );
    assert_eq!(
        preview_layout(&doc, &change).unwrap().font,
        format!("Noto Sans (the installed {NAME} could not be read)")
    );
}

/// `program` with `ch`'s advance moved by `units` font units.
fn moved(program: &[u8], ch: char, units: i16) -> Vec<u8> {
    let face = Face::parse(program, 0).unwrap();
    let id = face.glyph_index(ch).unwrap();
    let advance = face.glyph_hor_advance(id).unwrap();
    let mut program = program.to_vec();
    let at = table(&program, b"hmtx") + 4 * usize::from(id.0);
    program[at..at + 2].copy_from_slice(&advance.wrapping_add_signed(units).to_be_bytes());
    program
}

/// `program` with another OS/2 `fsType`.
fn rights_of(program: &[u8], rights: u16) -> Vec<u8> {
    let mut program = program.to_vec();
    let at = table(&program, b"OS/2") + 8;
    program[at..at + 2].copy_from_slice(&rights.to_be_bytes());
    program
}

/// The FontFile3 subtype of the added font's descendant, if it has one.
fn carrier(doc: &Document, child: &Dictionary) -> Option<Vec<u8>> {
    let descriptor = doc
        .get_dictionary(
            child
                .get(b"FontDescriptor")
                .unwrap()
                .as_reference()
                .unwrap(),
        )
        .unwrap();
    let stream = doc
        .get_object(descriptor.get(b"FontFile3").ok()?.as_reference().unwrap())
        .unwrap()
        .as_stream()
        .unwrap();
    Some(
        stream
            .dict
            .get(b"Subtype")
            .unwrap()
            .as_name()
            .unwrap()
            .to_vec(),
    )
}

/// The document's own font as a producer embeds an OpenType font in a simple
/// font: a WinAnsi Type1 font whose FontFile3 is a bare Type1C subset of the
/// same font.
fn type1c_document() -> Document {
    let mut doc = with_content(b"BT /F1 12 Tf 40 180 Td (TITLE) Tj 0 -80 Td (SECOND) Tj ET");
    let face = Face::parse(CFF, 0).unwrap();
    let widths = (32_u8..=84)
        .map(|code| {
            let ch = char::from(code);
            let width = if "TITLE SECOND".contains(ch) {
                f64::from(
                    face.glyph_hor_advance(face.glyph_index(ch).unwrap())
                        .unwrap(),
                )
            } else {
                0.
            };
            Object::Real(width as f32)
        })
        .collect::<Vec<_>>();
    let stream = doc.add_object(Stream::new(
        dictionary! { "Subtype" => "Type1C" },
        SUBSET_CFF.to_vec(),
    ));
    let tagged = format!("ABCDEF+{NAME}");
    let descriptor = doc.add_object(dictionary! {
        "Type" => "FontDescriptor", "FontName" => tagged.as_str(), "Flags" => 32,
        "FontBBox" => vec![0.into(), 0.into(), 1000.into(), 700.into()],
        "ItalicAngle" => 0, "Ascent" => 879, "Descent" => -195,
        "CapHeight" => 700, "StemV" => 80, "FontFile3" => stream
    });
    let font = doc.add_object(dictionary! {
        "Type" => "Font", "Subtype" => "Type1", "BaseFont" => tagged.as_str(),
        "Encoding" => "WinAnsiEncoding", "FirstChar" => 32, "LastChar" => 84,
        "Widths" => widths, "FontDescriptor" => descriptor
    });
    for page in crate::pagetree::ordered_pages(&doc) {
        doc.get_dictionary_mut(page).unwrap().set(
            "Resources",
            dictionary! { "Font" => dictionary! { "F1" => font } },
        );
    }
    doc
}

#[test]
fn cff_outlines_are_subsetted_and_embedded_as_a_cid_keyed_program() {
    let doc = document();
    let change = edit(&doc, "TITLE Ab", EditFont::Auto, Some(supplied(CFF, None)));
    let report = preview_layout(&doc, &change).unwrap();
    assert_eq!(report.font, USED);
    // The journal keeps an OpenType subset, the character map and the
    // rights put back, and it is itself an installed copy that sets the
    // same text the same way.
    let kept = report.installed.expect("the subset the journal keeps");
    assert_eq!(&kept.program[..4], b"OTTO");
    let face = Face::parse(&kept.program, 0).unwrap();
    let whole = Face::parse(CFF, 0).unwrap();
    assert!(face.tables().cff.is_some() && face.tables().glyf.is_none());
    assert_eq!(face.number_of_glyphs(), 13);
    assert!(carries_name(&face, NAME));
    assert!(face.raw_face().table(Tag::from_bytes(b"OS/2")).is_some());
    for ch in "TITLE SECONDAb".chars() {
        assert_eq!(
            face.glyph_hor_advance(face.glyph_index(ch).unwrap()),
            whole.glyph_hor_advance(whole.glyph_index(ch).unwrap()),
            "{ch}"
        );
    }
    // Unlike a TrueType one, a CFF subset of the subset is not the same
    // bytes: `subsetter` writes the Font DICT's matrix it read back at
    // another length. The second is a fixed point, with the same glyphs.
    let journal = edit(&doc, "TITLE Ab", EditFont::Auto, Some(kept.clone()));
    let again = preview_layout(&doc, &journal).unwrap();
    assert_eq!(again.font, USED);
    let second = again.installed.expect("a subset again");
    let resubset = edit(&doc, "TITLE Ab", EditFont::Auto, Some(second.clone()));
    assert_eq!(
        preview_layout(&doc, &resubset).unwrap().installed.as_ref(),
        Some(&second)
    );
    let face2 = Face::parse(&second.program, 0).unwrap();
    assert_eq!(face2.number_of_glyphs(), face.number_of_glyphs());
    for ch in "TITLE SECONDAb".chars() {
        assert_eq!(face2.glyph_index(ch), face.glyph_index(ch), "{ch}");
        assert_eq!(
            face2.glyph_hor_advance(face2.glyph_index(ch).unwrap()),
            face.glyph_hor_advance(face.glyph_index(ch).unwrap()),
            "{ch}"
        );
    }

    let mut saved = doc.clone();
    write(&mut saved, std::slice::from_ref(&change)).unwrap();
    let (font, child, program) = embedded(&saved);
    assert_eq!(
        child.get(b"Subtype").unwrap().as_name().unwrap(),
        b"CIDFontType0"
    );
    assert!(!child.has(b"CIDToGIDMap"));
    assert_eq!(
        carrier(&saved, &child).as_deref(),
        Some(&b"CIDFontType0C"[..])
    );
    // The bare program inside the subset the journal keeps, its rights
    // carried in the Top DICT as Distiller carries them.
    let table = face.raw_face().table(Tag::from_bytes(b"CFF ")).unwrap();
    assert_eq!(
        program,
        crate::textedit::fonts::cff::rights::with_rights(table, Some(0)).unwrap()
    );
    let declaration = b"/FSType 0 def /OrigFontType /OpenType def";
    assert!(program.windows(declaration.len()).any(|w| w == declaration));
    // Each code is the subset's glyph id, and each width the installed
    // advance of the character its ToUnicode entry names.
    let map = saved
        .get_object(font.get(b"ToUnicode").unwrap().as_reference().unwrap())
        .unwrap()
        .as_stream()
        .unwrap()
        .content
        .clone();
    let map = String::from_utf8(map).unwrap();
    let widths = child.get(b"W").unwrap().as_array().unwrap();
    assert_eq!(widths.len(), 2 * "TILE Ab".len());
    for pair in widths.chunks_exact(2) {
        let code = pair[0].as_i64().unwrap();
        let width = f64::from(pair[1].as_array().unwrap()[0].as_float().unwrap());
        let entry = format!("<{code:04X}> <");
        let at = map.find(&entry).expect("a ToUnicode entry") + entry.len();
        let ch = char::from_u32(u32::from_str_radix(&map[at..at + 4], 16).unwrap()).unwrap();
        assert_eq!(i64::from(face.glyph_index(ch).unwrap().0), code, "{ch}");
        let advance = f64::from(
            whole
                .glyph_hor_advance(whole.glyph_index(ch).unwrap())
                .unwrap(),
        );
        assert!(
            (advance - width).abs() < 1e-3,
            "{ch}: {width} against {advance}"
        );
    }

    // Saved and reopened, the written font is read as the document's own
    // CID-keyed CFF font: its glyphs set text with no installed copy at all.
    let mut bytes = Vec::new();
    saved.save_to(&mut bytes).unwrap();
    let mut reopened = Document::load_mem(&bytes).unwrap();
    assert_eq!(scan(&reopened, 0).unwrap().runs[0].text, "TITLE Ab");
    let own = preview_layout(
        &reopened,
        &edit(&reopened, "Ab TITLE", EditFont::Auto, None),
    )
    .unwrap();
    assert!(
        own.font.len() == NAME.len() + 7 && own.font.ends_with(&format!("+{NAME}")),
        "{}",
        own.font
    );
    assert_eq!((own.wants, own.installed), (None, None));
    // A character in neither subset goes back to the installed copy by name.
    let next = edit(&reopened, "TITLE Abz", EditFont::Auto, None);
    assert_eq!(
        preview_layout(&reopened, &next).unwrap().wants.as_deref(),
        Some(NAME)
    );
    let next = edit(
        &reopened,
        "TITLE Abz",
        EditFont::Auto,
        Some(supplied(CFF, None)),
    );
    assert_eq!(preview_layout(&reopened, &next).unwrap().font, USED);
    write(&mut reopened, &[next]).unwrap();
    let mut bytes = Vec::new();
    reopened.save_to(&mut bytes).unwrap();
    let reopened = Document::load_mem(&bytes).unwrap();
    assert_eq!(scan(&reopened, 0).unwrap().runs[0].text, "TITLE Abz");
}

#[test]
fn a_cff_copy_keeps_its_rights_in_the_embedded_program() {
    let doc = document();
    let refused = format!("Noto Sans (the installed {NAME} does not permit editing)");
    for (rights, expected) in [
        (0x8_u16, USED),
        (0x2, refused.as_str()),
        (0x4, &refused),
        (0x100, &refused),
        (0x200, &refused),
    ] {
        let program = rights_of(CFF, rights);
        let change = edit(
            &doc,
            "TITLE Ab",
            EditFont::Auto,
            Some(supplied(&program, None)),
        );
        assert_eq!(
            preview_layout(&doc, &change).unwrap().font,
            expected,
            "fsType {rights:#x}"
        );
        if expected == USED {
            let mut saved = doc.clone();
            write(&mut saved, &[change]).unwrap();
            let (_, _, program) = embedded(&saved);
            let declaration = b"/FSType 8 def /OrigFontType /OpenType def";
            assert!(program.windows(declaration.len()).any(|w| w == declaration));
            // Reopened, the program's own rights are read and permit editing.
            let mut bytes = Vec::new();
            saved.save_to(&mut bytes).unwrap();
            let reopened = Document::load_mem(&bytes).unwrap();
            let own = edit(&reopened, "Ab TITLE", EditFont::Auto, None);
            assert!(preview_layout(&reopened, &own)
                .unwrap()
                .font
                .ends_with(&format!("+{NAME}")));
        }
    }
}

#[test]
fn cff2_outlines_are_refused_with_their_own_reason() {
    let mut program = CFF.to_vec();
    let count = usize::from(u16::from_be_bytes([program[4], program[5]]));
    let record = (0..count)
        .map(|index| 12 + 16 * index)
        .find(|&at| &program[at..at + 4] == b"CFF ")
        .unwrap();
    program[record + 3] = b'2';
    let doc = document();
    let change = edit(
        &doc,
        "TITLE Ab",
        EditFont::Auto,
        Some(supplied(&program, None)),
    );
    assert_eq!(
        preview_layout(&doc, &change).unwrap().font,
        format!("Noto Sans (the installed {NAME} has CFF2 outlines, which cannot be embedded)")
    );
}

#[test]
fn a_cff_copy_whose_width_disagrees_falls_to_noto() {
    let doc = document();
    let differs = format!("Noto Sans (the installed {NAME} differs from the document's copy)");
    // `T` is 589.84 thousandths in the document and 590 units in the copy.
    for (units, expected) in [(0, USED), (3, differs.as_str()), (-3, &differs)] {
        let program = moved(CFF, 'T', units);
        let change = edit(
            &doc,
            "TITLE Ab",
            EditFont::Auto,
            Some(supplied(&program, None)),
        );
        assert_eq!(
            preview_layout(&doc, &change).unwrap().font,
            expected,
            "{units} units"
        );
    }
}

#[test]
fn a_cff_copy_whose_charstrings_disagree_with_its_metrics_is_not_embedded() {
    // `b` is in no document subset, so no width comparison sees it; only
    // reading the embedded program back against the widths `/W` would
    // declare does.
    let doc = document();
    let program = moved(CFF, 'b', 5);
    let change = edit(
        &doc,
        "TITLE Ab",
        EditFont::Auto,
        Some(supplied(&program, None)),
    );
    assert_eq!(
        preview_layout(&doc, &change).unwrap().font,
        format!("Noto Sans (the installed {NAME} could not be read)")
    );
}

#[test]
fn two_characters_one_cff_glyph_are_refused_with_their_own_reason() {
    // cff.otf draws U+00A0 with the space glyph; one CID cannot carry both
    // characters in a ToUnicode map.
    let doc = document();
    let change = edit(
        &doc,
        "TITLE A\u{a0}b",
        EditFont::Auto,
        Some(supplied(CFF, None)),
    );
    assert_eq!(
        preview_layout(&doc, &change).unwrap().font,
        format!("Noto Sans (the installed {NAME} draws two of the characters with one glyph)")
    );
    // Either one alone is set in the installed copy.
    for text in ["TITLE Ab", "TITLE\u{a0}Ab"] {
        let change = edit(&doc, text, EditFont::Auto, Some(supplied(CFF, None)));
        assert_eq!(
            preview_layout(&doc, &change).unwrap().font,
            USED,
            "{text:?}"
        );
    }
}

#[test]
fn a_cff_program_the_reader_would_refuse_is_not_embedded() {
    // The same font at 2048 units per em: its widths agree with the
    // document's, and its FontMatrix is one the CID-keyed CFF reader of a
    // reopened document refuses, so it is refused before anything is written.
    let doc = document();
    let change = edit(
        &doc,
        "TITLE Ab",
        EditFont::Auto,
        Some(supplied(CFF_2048, None)),
    );
    assert_eq!(
        preview_layout(&doc, &change).unwrap().font,
        format!("Noto Sans (the installed {NAME} could not be read)")
    );
}

#[test]
fn the_cff_writer_gives_every_character_its_own_glyph_code() {
    // A subset whose map draws U+00A0 and the space with one glyph, as the
    // journal keeps one when only one of them was typed: the writer, which
    // `accept` never asks for both, refuses both rather than map one code
    // to two characters. Its own layout check is what refuses: the later
    // character takes the shared code's text and the earlier cannot be
    // encoded (a separate check for it survived its mutation, 2026-09-30).
    let doc = document();
    let change = edit(
        &doc,
        "TITLE\u{a0}Ab",
        EditFont::Auto,
        Some(supplied(CFF, None)),
    );
    let kept = preview_layout(&doc, &change).unwrap().installed.unwrap();
    let face = Face::parse(&kept.program, 0).unwrap();
    assert_eq!(face.glyph_index(' '), face.glyph_index('\u{a0}'));
    assert!(fallback::Font::installed(kept.program.clone(), NAME, "A b").is_ok());
    assert!(fallback::Font::installed(kept.program, NAME, "A b\u{a0}").is_err());
}

#[test]
fn a_type1c_document_font_is_compared_with_its_installed_copy() {
    let doc = type1c_document();
    let asked = preview_layout(&doc, &edit(&doc, "TITLE Ab", EditFont::Auto, None)).unwrap();
    assert_eq!(asked.wants.as_deref(), Some(NAME));
    let differs = format!("Noto Sans (the installed {NAME} differs from the document's copy)");
    // The CFF copy itself, a TrueType build of the same font (widths within
    // half a unit), and a CFF copy three units off on a letter of the subset.
    for (program, expected) in [
        (CFF.to_vec(), USED),
        (FULL.to_vec(), USED),
        (moved(CFF, 'S', 3), differs.as_str()),
    ] {
        let change = edit(
            &doc,
            "TITLE Ab",
            EditFont::Auto,
            Some(supplied(&program, None)),
        );
        let report = preview_layout(&doc, &change).unwrap();
        assert_eq!(report.font, expected);
        if expected == USED {
            let mut saved = doc.clone();
            write(&mut saved, &[change]).unwrap();
            assert_eq!(scan(&saved, 0).unwrap().runs[0].text, "TITLE Ab");
        }
    }
}

#[test]
fn the_rights_writer_moves_every_offset_and_refuses_what_it_cannot_patch() {
    use crate::textedit::fonts::cff::{cid, rights::with_rights};
    let doc = document();
    let change = edit(&doc, "TITLE Ab", EditFont::Auto, Some(supplied(CFF, None)));
    let kept = preview_layout(&doc, &change).unwrap().installed.unwrap();
    let face = Face::parse(&kept.program, 0).unwrap();
    let bare = face.raw_face().table(Tag::from_bytes(b"CFF ")).unwrap();
    assert_eq!(with_rights(bare, None).unwrap(), bare);
    let before = cid::parse(bare).unwrap();
    // 0x100 is the no-subsetting bit, which a document's own font may carry.
    for rights in [0_u16, 8, 0x100] {
        let written = with_rights(bare, Some(rights)).unwrap();
        let after = cid::parse(&written).unwrap();
        // Every glyph reads back with the same width and outline hull.
        for cid in 0..face.number_of_glyphs() {
            let (old, new) = (before.glyph(cid).unwrap(), after.glyph(cid).unwrap());
            assert_eq!(
                old.map(|g| (g.id, g.advance, g.ink)),
                new.map(|g| (g.id, g.advance, g.ink)),
                "CID {cid}"
            );
        }
        // A second declaration is refused rather than duplicated.
        assert!(with_rights(&written, Some(rights)).is_err());
    }
    // A truncated program never panics, and never comes out as one the
    // reader accepts: the writer refuses what it cannot patch, and leaves
    // the rest to `cid::parse`, which the writer's caller runs.
    for len in 0..bare.len() {
        assert!(
            with_rights(&bare[..len], Some(8)).map_or(true, |w| cid::parse(&w).is_err()),
            "prefix {len}"
        );
    }
}

#[test]
fn a_character_the_installed_copy_lacks_goes_to_noto() {
    let doc = document();
    let change = edit(
        &doc,
        "TITLE \u{4e2d}",
        EditFont::Auto,
        Some(supplied(FULL, None)),
    );
    assert_eq!(
        preview_layout(&doc, &change).unwrap().font,
        format!("Noto Sans CJK SC (the installed {NAME} lacks a character)")
    );
    // Beyond Latin-1, but in the installed copy: the document's WinAnsi
    // subset could never have written it.
    let change = edit(
        &doc,
        "TITLE \u{3a9}\u{20ac}",
        EditFont::Auto,
        Some(supplied(FULL, None)),
    );
    let mut saved = doc.clone();
    assert_eq!(preview_layout(&doc, &change).unwrap().font, USED);
    write(&mut saved, &[change]).unwrap();
    assert_eq!(
        scan(&saved, 0).unwrap().runs[0].text,
        "TITLE \u{3a9}\u{20ac}"
    );
}

#[test]
fn a_document_font_that_forbids_editing_is_not_replaced_by_its_installed_copy() {
    let mut subset = SUBSET.to_vec();
    let at = table(&subset, b"OS/2") + 8;
    subset[at..at + 2].copy_from_slice(&2_u16.to_be_bytes());
    let doc = document_with(&subset);
    let change = edit(&doc, "TITLE Ab", EditFont::Auto, Some(supplied(FULL, None)));
    let report = preview_layout(&doc, &change).unwrap();
    assert_eq!(
        report.font,
        "Noto Sans (the document's font does not permit editing)"
    );
    assert_eq!((report.wants, report.installed), (None, None));
}

#[test]
fn the_name_asked_for_is_the_documents_without_its_subset_tag() {
    let doc = document();
    let page = crate::pagetree::ordered_pages(&doc)[0];
    let resources = doc.get_dictionary(page).unwrap().get(b"Resources").unwrap();
    let font = resources
        .as_dict()
        .unwrap()
        .get(b"Font")
        .unwrap()
        .as_dict()
        .unwrap()
        .get(b"F1")
        .unwrap();
    let font = doc
        .get_dictionary(font.as_reference().unwrap())
        .unwrap()
        .clone();
    assert_eq!(postscript_name(&doc, &font).as_deref(), Some(NAME));
    let descriptor = font.get(b"FontDescriptor").unwrap().as_reference().unwrap();
    for (name, expected) in [
        (NAME.to_owned(), Some(NAME)),
        // Five letters, or a lower-case one, is not a subset tag: the plus
        // sign is then part of the name, as PostScript allows.
        (format!("ABCDE+{NAME}"), Some("ABCDE+TPDFInstalledSans")),
        (format!("ABCDEf+{NAME}"), Some("ABCDEf+TPDFInstalledSans")),
        ("ABCDEF+Bad(Name)".to_owned(), None),
        ("ABCDEF+".to_owned() + &"N".repeat(64), None),
    ] {
        let mut doc = doc.clone();
        doc.get_dictionary_mut(descriptor)
            .unwrap()
            .set("FontName", Object::Name(name.clone().into_bytes()));
        assert_eq!(postscript_name(&doc, &font).as_deref(), expected, "{name}");
    }
    // A font that embeds nothing names no installed copy: its text is read-only.
    let mut bare = doc.clone();
    bare.get_dictionary_mut(descriptor)
        .unwrap()
        .remove(b"FontFile2");
    assert_eq!(postscript_name(&bare, &font), None);
    assert!(
        valid_postscript_name(NAME) && !valid_postscript_name("A B") && !valid_postscript_name("")
    );
}

/// macOS always has Arial and Helvetica, the second in a collection whose face
/// CoreText does not name. Exercises the lookup and the worker's face search
/// together, on real system files; the substitute CoreText answers an unknown
/// name with is refused by name.
#[cfg(target_os = "macos")]
#[test]
fn macos_finds_installed_fonts_by_exact_postscript_name() {
    let arial = crate::sysfont::find("ArialMT").expect("Arial ships with macOS");
    assert_eq!(arial.index, None);
    let at = face_index(&arial.bytes, arial.index, "ArialMT").unwrap();
    assert!(carries_name(
        &Face::parse(&arial.bytes, at).unwrap(),
        "ArialMT"
    ));
    let helvetica = crate::sysfont::find("Helvetica").expect("Helvetica ships with macOS");
    assert!(ttf_parser::fonts_in_collection(&helvetica.bytes).is_some_and(|n| n > 1));
    let at = face_index(&helvetica.bytes, None, "Helvetica").unwrap();
    assert!(carries_name(
        &Face::parse(&helvetica.bytes, at).unwrap(),
        "Helvetica"
    ));
    assert!(crate::sysfont::find("TPDFNoSuchFontAnywhere").is_none());
}

/// Windows always has Arial; DirectWrite names the face as well as the file.
#[cfg(windows)]
#[test]
fn windows_finds_installed_fonts_by_exact_postscript_name() {
    let arial = crate::sysfont::find("ArialMT").expect("Arial ships with Windows");
    let index = arial.index.expect("DirectWrite names the face");
    assert_eq!(face_index(&arial.bytes, Some(index), "ArialMT"), Ok(index));
    assert!(crate::sysfont::find("TPDFNoSuchFontAnywhere").is_none());
}

#[test]
fn an_installed_font_crosses_the_worker_boundary_as_one_bounded_string() {
    let installed = supplied(FULL, Some(1));
    let json = serde_json::to_value(&installed).unwrap();
    assert!(json["program"].is_string());
    assert_eq!(
        serde_json::from_value::<Installed>(json).unwrap(),
        installed
    );
    // The longest string that can decode to the bound, and one quantum more,
    // refused before anything is decoded.
    let limit = MAX_BYTES.div_ceil(3) * 4;
    let at = serde_json::json!({ "name": NAME, "program": "A".repeat(limit) });
    assert!(serde_json::from_value::<Installed>(at).is_ok());
    let past = serde_json::json!({ "name": NAME, "program": "A".repeat(limit + 4) });
    assert!(serde_json::from_value::<Installed>(past).is_err());
    // A layout written before the field existed reads as one without it.
    let layout: Layout = serde_json::from_str(
        r#"{"width":1,"height":1,"size":12,"wrap":false,"font":"auto","grow":false}"#,
    )
    .unwrap();
    assert_eq!(layout.installed, None);
    assert!(!serde_json::to_string(&layout)
        .unwrap()
        .contains("installed"));
}

#[test]
fn a_colour_font_is_refused_with_its_own_reason() {
    let doc = document();
    let change = edit(
        &doc,
        "TITLE Ab",
        EditFont::Auto,
        Some(supplied(COLOUR, None)),
    );
    assert_eq!(
        preview_layout(&doc, &change).unwrap().font,
        format!("Noto Sans (the installed {NAME} is a variable or colour font)")
    );
}

/// `FULL` with its Macintosh PostScript name record changed by one letter,
/// while the Unicode and Windows records still read the right name.
fn with_disagreeing_names() -> Vec<u8> {
    let mut program = FULL.to_vec();
    let at = table(&program, b"name");
    let count = usize::from(u16::from_be_bytes([program[at + 2], program[at + 3]]));
    let storage = at + usize::from(u16::from_be_bytes([program[at + 4], program[at + 5]]));
    let record = (0..count)
        .map(|index| at + 6 + 12 * index)
        .find(|&record| {
            let field = |offset: usize| {
                u16::from_be_bytes([program[record + offset], program[record + offset + 1]])
            };
            field(0) == 1 && field(6) == 6
        })
        .expect("a Macintosh PostScript name record");
    let length = usize::from(u16::from_be_bytes([
        program[record + 8],
        program[record + 9],
    ]));
    let offset = usize::from(u16::from_be_bytes([
        program[record + 10],
        program[record + 11],
    ]));
    let last = storage + offset + length - 1;
    assert_eq!(program[last], b's');
    program[last] = b'z';
    program
}

#[test]
fn a_face_whose_name_records_disagree_is_not_the_font() {
    let doc = document();
    let unreadable = format!("Noto Sans (the installed {NAME} could not be read)");
    let program = with_disagreeing_names();
    let change = edit(
        &doc,
        "TITLE Ab",
        EditFont::Auto,
        Some(supplied(&program, None)),
    );
    assert_eq!(preview_layout(&doc, &change).unwrap().font, unreadable);
    // And the Macintosh record alone is read: the same change to it alone
    // names a font the document did not ask for.
    let face = Face::parse(&program, 0).unwrap();
    assert!(!carries_name(&face, NAME));
    assert!(!carries_name(&face, "TPDFInstalledSanz"));
}

#[test]
fn a_document_subset_that_declares_no_width_has_nothing_to_compare() {
    assert_eq!(
        accept(&supplied(FULL, None), NAME, &[], "Ab").err(),
        Some(Refusal::Widths)
    );
    assert!(accept(&supplied(FULL, None), NAME, &[('T', 589.84375)], "Ab").is_ok());
}

/// macOS ships OpenType fonts with CFF outlines in its sealed system volume:
/// Hiragino Sans, CID-keyed with `fsType` 8, as a face of a collection
/// CoreText does not name, and Kohinoor Devanagari, name-keyed with `fsType`
/// 0. Each is subsetted, embedded, and read back by the reader a reopened
/// document goes through. Tamil Sangam MN's CFF is drawn at 2048 units per
/// em, a matrix that reader refuses, so it is refused before anything is
/// written.
#[cfg(target_os = "macos")]
#[test]
fn macos_embeds_installed_cff_fonts_through_the_reader_a_reopened_document_uses() {
    for (name, text, rights) in [
        ("HiraginoSans-W3", "Tokyo \u{6771}\u{4eac}", Some(8)),
        ("KohinoorDevanagari-Regular", "Mumbai \u{915}", Some(0)),
        ("TamilSangamMN", "Tamil", None),
    ] {
        let found = crate::sysfont::find(name).expect("ships with macOS");
        let at = face_index(&found.bytes, found.index, name).unwrap();
        let face = Face::parse(&found.bytes, at).unwrap();
        assert!(face.tables().cff.is_some(), "{name} has CFF outlines");
        // What a producer's subset of it declares: integer widths.
        let unit = 1000. / f64::from(face.units_per_em());
        let declared = "Tamo"
            .chars()
            .map(|ch| {
                let advance = face
                    .glyph_hor_advance(face.glyph_index(ch).unwrap())
                    .unwrap();
                (ch, (f64::from(advance) * unit).round())
            })
            .collect::<Vec<_>>();
        let supplied = Installed {
            name: name.into(),
            index: found.index,
            program: found.bytes.clone(),
        };
        let result = accept(&supplied, name, &declared, text);
        let Some(rights) = rights else {
            assert_eq!(result.err(), Some(Refusal::Unreadable), "{name}");
            continue;
        };
        let accepted = result.unwrap_or_else(|refusal| panic!("{name}: {refusal:?}"));
        assert!(
            accepted.program.program.len() * 100 < found.bytes.len(),
            "{name}"
        );
        let mut doc = with_content(b"BT ET");
        let id = accepted
            .font
            .install(
                &mut doc,
                &mut crate::textedit::fonts::fallback::Programs::new(),
            )
            .unwrap();
        let written = doc.get_dictionary(id).unwrap().clone();
        let metrics = super::super::composite(&doc, &written).unwrap();
        let mut read = metrics.declared();
        read.sort_by_key(|(ch, _)| *ch);
        let mut expected = text
            .chars()
            .collect::<std::collections::BTreeSet<_>>()
            .into_iter()
            .map(|ch| {
                let advance = face
                    .glyph_hor_advance(face.glyph_index(ch).unwrap())
                    .unwrap();
                (ch, f64::from(advance) * unit)
            })
            .collect::<Vec<_>>();
        expected.sort_by_key(|(ch, _)| *ch);
        assert_eq!(read.len(), expected.len(), "{name}");
        for ((ch, width), (want, advance)) in read.iter().zip(&expected) {
            assert_eq!(ch, want, "{name}");
            assert!(
                (width - advance).abs() < 1e-3,
                "{name} {ch}: {width} against {advance}"
            );
        }
        let (_, child, program) = embedded_font(&doc, &written);
        assert_eq!(
            carrier(&doc, &child).as_deref(),
            Some(&b"CIDFontType0C"[..])
        );
        let declaration = format!("/FSType {rights} def /OrigFontType /OpenType def");
        assert!(
            program
                .windows(declaration.len())
                .any(|w| w == declaration.as_bytes()),
            "{name}"
        );
    }
}
