/**
 * Noticing that another program rewrote the open file, and what to do about it.
 *
 * A document's bytes are mapped when it opens. A file replaced by rename ---
 * which is how nearly every program writes one --- leaves the mapping holding
 * the old file, so every page keeps rendering as it did and nothing in the
 * render path can say the file moved on. Until this module the reader found out
 * when a save or a print was refused.
 *
 * Three parts, and they are here rather than in `App.svelte` because nothing
 * renders that component:
 *
 * - {@link DiskWatch} decides *whether* the file changed, from two questions
 *   the backend answers: a `stat` at open against a `stat` now, and, only when
 *   those differ, a comparison by content.
 * - {@link afterDiskChange} decides *what happens*: a prompt, a reload, or
 *   nothing.
 * - {@link readDiskChangeMode} is the reader's choice between those, kept in
 *   `localStorage` under {@link MODE_KEY} the way `signtimestamp.ts` keeps its
 *   own.
 */

import type { Prompt } from "./recovery";

/**
 * What the reader wants done when the open file changes on disk.
 *
 * - `ask`: say so, and offer Reload. The default.
 * - `reload`: reload without asking, unless there are unsaved edits.
 * - `ignore`: do not look.
 */
export type DiskChangeMode = "ask" | "reload" | "ignore";

/** Every mode, in the order the commands list them. */
export const DISK_CHANGE_MODES: readonly DiskChangeMode[] = ["ask", "reload", "ignore"];

/** What a reader who has never chosen gets. */
export const DEFAULT_DISK_CHANGE_MODE: DiskChangeMode = "ask";

/** Where the choice lives. */
export const MODE_KEY = "tpdf.onDiskChange";

type Store = Pick<Storage, "getItem" | "setItem">;

/**
 * The remembered mode, or the default. Storage that throws, or that holds
 * anything tpdf did not write, reads as the default.
 */
export function readDiskChangeMode(
  storage: () => Store = () => window.localStorage,
): DiskChangeMode {
  let raw: string | null;
  try {
    raw = storage().getItem(MODE_KEY);
  } catch {
    return DEFAULT_DISK_CHANGE_MODE;
  }
  return DISK_CHANGE_MODES.find((mode) => mode === raw) ?? DEFAULT_DISK_CHANGE_MODE;
}

/** Keeps `mode`; `false` when storage refused, which changes nothing now. */
export function writeDiskChangeMode(
  mode: DiskChangeMode,
  storage: () => Store = () => window.localStorage,
): boolean {
  try {
    storage().setItem(MODE_KEY, mode);
    return true;
  } catch {
    return false;
  }
}

/**
 * What to do about a file that changed on disk: a prompt to show, `"reload"`
 * to reload without asking, or `null` for nothing.
 *
 * **Unsaved edits always get the prompt, whatever the mode.** A reload spends
 * the journal, and "reload automatically" was chosen for a document being
 * regenerated by another program, not as permission to discard work. Save a
 * copy leads, as it does in every prompt `recovery.ts` builds.
 */
export function afterDiskChange(
  mode: DiskChangeMode,
  dirty: boolean,
  name: string,
): Prompt | "reload" | null {
  if (mode === "ignore") return null;
  if (dirty) {
    return {
      message:
        `${name} changed on disk while you have unsaved edits. ` +
        "Save a copy to keep them; reloading discards them.",
      offers: ["saveCopy", "reload"],
    };
  }
  if (mode === "reload") return "reload";
  return { message: `${name} changed on disk.`, offers: ["reload"] };
}

/** What {@link onDiskChange} needs from the window. */
export interface DiskChangeHost {
  /** The reader's choice. */
  mode(): DiskChangeMode;
  /** The document's name, for the sentence. */
  name(): string;
  /**
   * Commits whatever the reader is still typing and waits for the edit that
   * makes. Rejects when a draft cannot be committed.
   */
  settle(): Promise<void>;
  /** Whether the document has edits that are not in the file. */
  dirty(): boolean;
  /**
   * Whether the document the change was reported for is still the one open,
   * with nothing opening and no save running. Asked again after the wait.
   */
  current(): boolean;
  /** Reloads the document, warning already given or not needed. */
  reload(): void;
  /** Shows a prompt with its offers. */
  say(prompt: Prompt): void;
}

/**
 * Acts on a file that changed on disk, and answers whether it did.
 *
 * **Before a reload nobody is asked about, the drafts are settled and `dirty`
 * is read again.** An answer being typed into a form field, or a note in its
 * box, is not an edit until something commits it, so the document reads as
 * unedited with the reader's words on screen --- and the reload itself commits
 * them, into the model it is about to close. Settling first makes them the
 * unsaved edit they are, which {@link afterDiskChange} answers with the prompt.
 * A draft that cannot be committed is work at stake all the same.
 *
 * Only on that one route. A prompt reloads nothing, and committing a draft
 * closes the box it is being typed in, which is not worth doing to a reader
 * to show them a sentence.
 *
 * `false` is "not now": the wait let another document or a save in, so
 * nothing was done and {@link DiskWatch} reports the change again.
 */
export async function onDiskChange(host: DiskChangeHost): Promise<boolean> {
  const mode = host.mode();
  let dirty = host.dirty();
  if (mode === "reload" && !dirty) {
    try {
      await host.settle();
      dirty = host.dirty();
    } catch {
      dirty = true;
    }
    if (!host.current()) return false;
  }
  const next = afterDiskChange(mode, dirty, host.name());
  if (next === "reload") host.reload();
  else if (next) host.say(next);
  return true;
}

/** The two questions the backend answers. `ipc.ts` has the commands. */
export interface DiskProbe {
  /**
   * The file's length-and-time stamp at open and now; either is `null` when it
   * could not be read.
   */
  stamp(doc: number, path: string): Promise<[string | null, string | null]>;
  /** Whether the file's bytes differ from what was opened; `null` for cannot tell. */
  differs(doc: number, path: string): Promise<boolean | null>;
}

/**
 * Decides when an open document's file has changed, and reports it once.
 *
 * {@link check} is called on a timer. What it holds between calls:
 *
 * - **`seen`**: the last stamp that differed from the open one. A change is
 *   acted on only when two consecutive checks read the same stamp, so a
 *   program still writing the file in place is waited for rather than
 *   reloaded half-written.
 * - **`judged`**: the stamp a verdict was already reached on. A changed file is
 *   reported once, and a file whose timestamp moved with its bytes intact ---
 *   a sync client, a backup tool --- is compared by content once, not once a
 *   second.
 *
 * Both reset when the document changes or the file returns to its open stamp.
 */
export class DiskWatch {
  private doc = -1;
  private seen: string | null = null;
  private judged: string | null = null;
  private checking = false;

  /**
   * @param report told a document's file changed. Answers whether it acted;
   *   `false` means "not now" (a save is running, another document is open) and
   *   the change is reported again on a later check. It may take its time
   *   answering --- {@link onDiskChange} waits for drafts to settle --- and the
   *   check is not over until it has.
   */
  constructor(
    private readonly probe: DiskProbe,
    private readonly report: (doc: number) => boolean | Promise<boolean>,
  ) {}

  /** One look at `doc`'s file. Never rejects; overlapping calls are dropped. */
  async check(doc: number, path: string): Promise<void> {
    if (this.checking) return;
    this.checking = true;
    try {
      if (doc !== this.doc) {
        this.doc = doc;
        this.seen = null;
        this.judged = null;
      }
      const [opened, now] = await this.probe.stamp(doc, path);
      // Cannot tell is not "changed": a file that is briefly missing while it
      // is being replaced must not reach a reload that would find nothing.
      if (opened === null || now === null) return;
      if (now === opened) {
        this.seen = null;
        this.judged = null;
        return;
      }
      if (now === this.judged) return;
      if (now !== this.seen) {
        this.seen = now;
        return;
      }
      // The stamp differs and held still for a whole interval. Only now is the
      // file read. `null` counts as changed: the stamp already says it is.
      if ((await this.probe.differs(doc, path)) === false) {
        this.judged = now;
        return;
      }
      if (await this.report(doc)) this.judged = now;
    } catch {
      // A failed question is no answer. The next check asks again.
    } finally {
      this.checking = false;
    }
  }
}
