/**
 * Puts the window into each state the README shows, one after another.
 *
 * `scripts/screenshots.py` is the other half: it launches a check build with
 * `TPDF_OPENCHECK=screenshots:<demo.pdf>|<signed.pdf>|<regions>`, reads this
 * phase's transcript as it is written, and captures the window each time a
 * `SHOT <name>` line appears. So the pictures in `docs/img/` are regenerated by
 * one command and show the application as it is, not as it was when somebody
 * last pressed a key combination.
 *
 * **The window holds each state for {@link HOLD_MS}**, which is the whole
 * protocol: the webview cannot be told when the capture finished, and a file
 * to wait on would need a command only this phase used.
 *
 * Every held state is also a frame of `docs/img/demo.gif`: the line is
 * `FRAME <index> <milliseconds shown> [<still name>]`, and the five that carry
 * a name are the stills. The frames between them are the steps a still skips
 * --- the palette being typed into, the marks arriving one at a time --- so
 * the animation is the same run, not a second script that could show
 * something the stills do not.
 *
 * Marks and regions go through `host.apply`, the application's own edit path,
 * and not through the model alone: the first run marked the model, every check
 * was green, and the pictures showed an untouched page beside an empty list.
 */

import { pause, settle, type Report } from "./checkreport";
import type { OpenCheckHost } from "./opencheck";

/** How long each state stays on screen for the capture. */
const HOLD_MS = 1200;
const SETTLE_MS = 20_000;

type Region = [number, number, number, number];

export async function screenshotCheck(
  host: OpenCheckHost,
  expected: string,
  report: Report,
): Promise<void> {
  const [demo, signed, encoded] = expected.split("|");
  if (!demo || !signed || !encoded) {
    throw new Error("the demo document, a signed document and the regions are required");
  }
  const regions = JSON.parse(encoded) as Record<string, Region>;
  const region = (name: string): Region => {
    const found = regions[name];
    if (!found) throw new Error(`no region named ${name}`);
    return found;
  };
  const quiet = async () => {
    if (!(await settle(() => host.viewer()?.idle === true, SETTLE_MS))) {
      throw new Error("the viewer did not settle");
    }
    await pause(300);
  };
  let frames = 0;
  /** Holds the window as it is; `shown` is how long the animation stays on it. */
  const frame = async (shown: number, still = "") => {
    await quiet();
    report.emit(`FRAME ${frames++} ${shown} ${still}`.trimEnd());
    await pause(HOLD_MS);
  };
  const shot = async (name: string, shown = 1800) => {
    await frame(shown, name);
    report.check(`held the window for ${name}`, true, "");
  };

  // ---- Reading: the document, its pages beside it.
  await host.open(demo); await host.idle(); await quiet();
  host.run("view.showThumbnails"); await host.idle();
  host.viewer()!.setFit("width");
  await shot("reading");

  // ---- The command palette, mid-question.
  const button = [...document.querySelectorAll<HTMLButtonElement>("button")].find(
    (b) => b.textContent === "Commands",
  );
  if (!button) throw new Error("the toolbar has no Commands button");
  button.click();
  const field = () => document.querySelector<HTMLInputElement>(".tpdf-palette input");
  if (!(await settle(() => field() !== null && field()!.offsetParent !== null, 5000))) {
    throw new Error("the palette did not open");
  }
  await frame(500);
  // Typed a letter at a time for the animation; the still is the last one.
  for (const typed of ["r", "re", "red", "reda", "redac"]) {
    field()!.value = typed;
    field()!.dispatchEvent(new InputEvent("input", { bubbles: true }));
    await frame(160);
  }
  field()!.value = "redact";
  field()!.dispatchEvent(new InputEvent("input", { bubbles: true }));
  await shot("palette");
  field()!.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", bubbles: true, cancelable: true }));
  await pause(200);

  // ---- Marks: a highlight, a box and a comment, listed in the sidebar.
  const model = host.edits()!;
  const page = model.state.pages[0]!.id;
  host.run("view.showMarks"); await host.idle();
  await host.apply((e) => e.mark("highlight", page, region("highlight")));
  await host.idle(); await frame(800);
  await host.apply((e) => e.mark("square", page, region("box")));
  await host.idle(); await frame(800);
  await host.apply((e) =>
    e.mark("note", page, region("note"), [], "North Pier is above the design level."));
  await host.idle();
  report.check("three marks reached the model", host.edits()!.state.marks.length === 3,
    String(host.edits()!.state.marks.length));
  await shot("annotate");

  // ---- Redaction: two regions marked and listed, nothing removed yet.
  host.run("view.showRedactions"); await host.idle();
  await host.apply((e) => e.redact(page, region("redact_name")));
  await host.idle(); await frame(800);
  await host.apply((e) => e.redact(page, region("redact_mail")));
  await host.idle();
  report.check("two regions reached the review list", host.edits()!.state.redactions.length === 2,
    String(host.edits()!.state.redactions.length));
  await shot("redact");

  // ---- Signatures: a document two people signed, one card each.
  await host.open(signed); await host.idle(); await quiet();
  host.run("file.properties");
  const cards = () => document.querySelectorAll<HTMLDetailsElement>(".tpdf-properties details");
  if (!(await settle(() => cards().length > 1, SETTLE_MS))) {
    throw new Error("the properties dialog showed no signature cards");
  }
  // Both closed: two cards on one screen is what the picture is of, and an
  // open one pushes the other out of sight.
  await shot("signatures");
  // And one opened, which only the animation shows.
  cards()[0]!.open = true;
  await frame(2600);
}
