use super::*;
use crate::textedit::{self, Change};
use lopdf::{dictionary, Stream};

// Generated by testdata/make_textedit_embedded.py from original geometric
// outlines; MIT like this repository. Contains no installed font material.
pub(super) const SYNTHETIC: &[u8] = include_bytes!("../synthetic.ttf");

pub(crate) fn fixture() -> (Document, lopdf::ObjectId, lopdf::ObjectId, lopdf::ObjectId) {
    let mut doc = textedit::tests::fixture();
    let program = doc.add_object(Stream::new(Dictionary::new(), SYNTHETIC.to_vec()));
    let descriptor = doc.add_object(dictionary! {
        "Type" => "FontDescriptor", "FontName" => "TPDFSynthetic", "Flags" => 32,
        "FontBBox" => vec![0.into(), 0.into(), 400.into(), 700.into()],
        "ItalicAngle" => 0, "Ascent" => 800, "Descent" => -200,
        "CapHeight" => 700, "StemV" => 100, "FontFile2" => program
    });
    let font = doc.add_object(dictionary! {
        "Type" => "Font", "Subtype" => "TrueType", "BaseFont" => "TPDFSynthetic",
        "Encoding" => "WinAnsiEncoding", "FirstChar" => 32, "LastChar" => 89,
        "Widths" => vec![Object::Integer(600); 58], "FontDescriptor" => descriptor
    });
    for page in crate::pagetree::ordered_pages(&doc) {
        doc.get_dictionary_mut(page).unwrap().set(
            "Resources",
            dictionary! { "Font" => dictionary! { "F1" => font } },
        );
    }
    (doc, font, descriptor, program)
}

fn change(doc: &Document, replacement: &str) -> Change {
    let runs = textedit::scan(doc, 0).unwrap();
    Change {
        layout: None,
        page: 0,
        operator: runs.runs[0].operator,
        revision: runs.revision,
        original: runs.runs[0].text.clone(),
        replacement: replacement.into(),
    }
}

pub(super) fn mac_fixture(missing_os2: bool) -> (Document, lopdf::ObjectId, lopdf::ObjectId) {
    let (mut doc, font, _, program) = fixture();
    let face = Face::parse(SYNTHETIC, 0).unwrap();
    let mut cmap = vec![0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 12];
    for value in [6_u16, 126, 0, 32, 58] {
        cmap.extend(value.to_be_bytes());
    }
    for code in 32_u8..=89 {
        cmap.extend(
            face.glyph_index(char::from(code))
                .map_or(0, |g| g.0)
                .to_be_bytes(),
        );
    }
    let mut bytes = SYNTHETIC.to_vec();
    bytes[..4].copy_from_slice(b"true");
    let offset = bytes.len() as u32;
    let count = u16::from_be_bytes(bytes[4..6].try_into().unwrap()) as usize;
    for record in bytes[12..12 + 16 * count].chunks_exact_mut(16) {
        if &record[..4] == b"cmap" {
            record[8..12].copy_from_slice(&offset.to_be_bytes());
            record[12..16].copy_from_slice(&(cmap.len() as u32).to_be_bytes());
        }
        if missing_os2 && &record[..4] == b"OS/2" {
            record[..4].copy_from_slice(b"NONE");
        }
    }
    bytes.extend(cmap);
    assert_eq!(
        Face::parse(&bytes, 0)
            .unwrap()
            .raw_face()
            .table(Tag::from_bytes(b"OS/2"))
            .is_none(),
        missing_os2
    );
    doc.get_object_mut(program)
        .unwrap()
        .as_stream_mut()
        .unwrap()
        .content = bytes;
    doc.get_dictionary_mut(font)
        .unwrap()
        .set("Encoding", "MacRomanEncoding");
    (doc, font, program)
}

#[test]
fn textedit_macroman_format6_preserves_font_and_refuses_notdef() {
    for missing_os2 in [false, true] {
        let (mut doc, font, program) = mac_fixture(missing_os2);
        let before = doc.objects.clone();
        assert!((textedit::scan(&doc, 0).unwrap().runs[0].advance - 108.).abs() < 1e-8);
        for missing in ["!", "ä", "Z"] {
            let update = change(&doc, missing);
            assert!(textedit::write(&mut doc, &[update])
                .unwrap_err()
                .contains("no validated glyph"));
            assert_eq!(doc.objects, before);
        }
        let update = change(&doc, "EDITED FIRST");
        textedit::write(&mut doc, &[update]).unwrap();
        assert_eq!(
            textedit::scan(&doc, 0).unwrap().runs[0].text,
            "EDITED FIRST"
        );
        for id in [font, program] {
            assert_eq!(doc.objects[&id], before[&id]);
        }
    }
}

#[test]
fn textedit_macroman_requires_matching_encoding_and_honours_present_rights() {
    for rights in [2_u16, 4, 0x200] {
        let (mut doc, _, program) = mac_fixture(false);
        let bytes = &mut doc
            .get_object_mut(program)
            .unwrap()
            .as_stream_mut()
            .unwrap()
            .content;
        let offset = table_offset(b"OS/2") + 8;
        bytes[offset..offset + 2].copy_from_slice(&rights.to_be_bytes());
        assert!(textedit::scan(&doc, 0)
            .unwrap_err()
            .contains("editable use"));
    }
    let (mut doc, font, program) = mac_fixture(true);
    doc.get_dictionary_mut(font)
        .unwrap()
        .set("Encoding", "WinAnsiEncoding");
    assert!(textedit::scan(&doc, 0).is_err());
    doc.get_dictionary_mut(font)
        .unwrap()
        .set("Encoding", "MacRomanEncoding");
    doc.get_object_mut(program)
        .unwrap()
        .as_stream_mut()
        .unwrap()
        .content[..4]
        .copy_from_slice(&[0, 1, 0, 0]);
    assert!(textedit::scan(&doc, 0).is_err());
}

#[test]
fn textedit_embedded_kerning_uses_validated_glyphs_and_own_widths() {
    let (mut doc, font, descriptor, program) = fixture();
    let page = crate::pagetree::ordered_pages(&doc)[0];
    let stream = doc.add_object(Stream::new(
        Dictionary::new(),
        b"BT /F1 12 Tf 40 180 Td [(A) 100 (B)] TJ ET".to_vec(),
    ));
    doc.get_dictionary_mut(page)
        .unwrap()
        .set("Contents", stream);
    assert!((textedit::scan(&doc, 0).unwrap().runs[0].advance - 13.2).abs() < 1e-8);
    let before = doc.objects.clone();
    let invalid = change(&doc, "Z");
    assert!(textedit::write(&mut doc, &[invalid])
        .unwrap_err()
        .contains("no validated glyph"));
    assert_eq!(doc.objects, before);
    let valid = change(&doc, "A");
    textedit::write(&mut doc, &[valid]).unwrap();
    assert_eq!(textedit::scan(&doc, 0).unwrap().runs[0].text, "A");
    for id in [font, descriptor, program] {
        assert_eq!(doc.objects[&id], before[&id]);
    }
    let missing = doc.add_object(Stream::new(
        Dictionary::new(),
        b"BT /F1 12 Tf 40 180 Td [(A) 10 (Z)] TJ ET".to_vec(),
    ));
    doc.get_dictionary_mut(page)
        .unwrap()
        .set("Contents", missing);
    assert!(textedit::scan(&doc, 0)
        .unwrap_err()
        .contains("no validated glyph"));
}

#[test]
fn textedit_embedded_subset_uses_own_widths_and_preserves_every_font_byte() {
    let (mut doc, font, descriptor, program) = fixture();
    let before = doc.objects.clone();
    let runs = textedit::scan(&doc, 0).unwrap();
    assert!((runs.runs[0].advance - 15. * 7.2).abs() < 1e-8);
    let update = change(&doc, "EDITED FIRST");
    textedit::write(&mut doc, &[update]).unwrap();
    assert_eq!(
        textedit::scan(&doc, 0).unwrap().runs[0].text,
        "EDITED FIRST"
    );
    assert_eq!(textedit::scan(&doc, 1).unwrap().runs, runs.runs);
    for id in [font, descriptor, program] {
        assert_eq!(doc.objects[&id], before[&id]);
    }
    // Export through the real serializer for independent readback when wanted.
    if let Some(path) = std::env::var_os("TPDF_EMBEDDED_PROBE") {
        doc.save(path).unwrap();
    }
}

#[test]
fn textedit_embedded_missing_glyph_and_own_width_overflow_leave_document_untouched() {
    for (replacement, reason) in [
        ("Z", "no validated glyph"),
        ("ä", "no validated glyph"),
        ("A A A A A A A AA", "exceed the original"),
    ] {
        let (mut doc, _, _, _) = fixture();
        let before = doc.objects.clone();
        let update = change(&doc, replacement);
        assert!(textedit::write(&mut doc, &[update])
            .unwrap_err()
            .contains(reason));
        assert_eq!(doc.objects, before);
    }
}

#[test]
fn textedit_graphics_restore_uses_the_active_font_for_replacement() {
    let (mut doc, font, _, _) = fixture();
    let page = crate::pagetree::ordered_pages(&doc)[0];
    // The raw name is not UTF-8. Neither the last Tf nor the lossy UI name
    // identifies the active embedded font after Q restores it.
    let mut fonts = dictionary! { "F2" => dictionary! {
        "Type" => "Font", "Subtype" => "Type1", "BaseFont" => "Helvetica", "Encoding" => "WinAnsiEncoding"
    }};
    fonts.set(b"F\xff".to_vec(), font);
    let stream = doc.add_object(Stream::new(
        Dictionary::new(),
        b"BT /F#ff 12 Tf ET q BT /F2 12 Tf ET Q BT 40 180 Td (AB) Tj ET".to_vec(),
    ));
    let page = doc.get_dictionary_mut(page).unwrap();
    page.set("Resources", dictionary! { "Font" => fonts });
    page.set("Contents", stream);
    let before = doc.objects.clone();
    let missing = change(&doc, "i");
    assert!(textedit::write(&mut doc, &[missing])
        .unwrap_err()
        .contains("no validated glyph"));
    assert_eq!(doc.objects, before);
    let valid = change(&doc, "BA");
    textedit::write(&mut doc, &[valid]).unwrap();
    assert_eq!(textedit::scan(&doc, 0).unwrap().runs[0].text, "BA");
}

#[test]
fn textedit_embedded_refuses_ambiguous_pdf_mappings_and_custom_metrics() {
    for (key, value) in [
        ("ToUnicode", Object::Null),
        ("Encoding", Object::Name(b"MacRomanEncoding".to_vec())),
        ("FirstChar", Object::Integer(-1)),
        ("LastChar", Object::Integer(256)),
        ("Widths", Object::Array(vec![600.into()])),
        ("Widths", Object::Array(vec![200.into(); 58])),
        ("Widths", Object::Array(vec![700.into(); 58])),
    ] {
        let (mut doc, font, _, _) = fixture();
        doc.get_dictionary_mut(font).unwrap().set(key, value);
        assert!(textedit::scan(&doc, 0).is_err(), "accepted {key}");
    }
    for flags in [0, 4, 36, 32 | 262144] {
        let (mut doc, _, descriptor, _) = fixture();
        doc.get_dictionary_mut(descriptor)
            .unwrap()
            .set("Flags", flags);
        assert!(textedit::scan(&doc, 0).is_err());
    }
}

#[test]
fn textedit_embedded_zero_width_holes_do_not_disable_other_glyphs() {
    let (mut doc, font, _, _) = fixture();
    doc.get_dictionary_mut(font)
        .unwrap()
        .get_mut(b"Widths")
        .unwrap()
        .as_array_mut()
        .unwrap()[(b'B' - 32) as usize] = 0.into();
    let metrics = embedded(&doc, doc.get_dictionary(font).unwrap()).unwrap();
    assert!(metrics.advance("B", 12.).is_err());
    assert!(metrics.source_layout(b"B", 12., 0., 0.).is_err());
    let edit = change(&doc, "IN");
    let before = doc.objects.clone();
    let mut bad = edit.clone();
    bad.replacement = "B".into();
    assert!(textedit::write(&mut doc, &[bad]).is_err());
    assert_eq!(doc.objects, before);
    textedit::write(&mut doc, &[edit]).unwrap();
    assert_eq!(textedit::scan(&doc, 0).unwrap().runs[0].text, "IN");
    assert_eq!(doc.objects[&font], before[&font]);
}

fn table_offset(tag: &[u8; 4]) -> usize {
    let count = u16::from_be_bytes(SYNTHETIC[4..6].try_into().unwrap()) as usize;
    for record in SYNTHETIC[12..12 + 16 * count].chunks_exact(16) {
        if &record[..4] == tag {
            return u32::from_be_bytes(record[8..12].try_into().unwrap()) as usize;
        }
    }
    panic!("missing synthetic table");
}

#[test]
fn textedit_embedded_refuses_restricted_missing_or_corrupt_programs() {
    for rights in [1_u16, 2, 4, 12, 0x200, 0x8000] {
        let (mut doc, _, _, program) = fixture();
        let stream = doc
            .get_object_mut(program)
            .unwrap()
            .as_stream_mut()
            .unwrap();
        let start = table_offset(b"OS/2") + 8;
        stream.content[start..start + 2].copy_from_slice(&rights.to_be_bytes());
        assert!(textedit::scan(&doc, 0)
            .unwrap_err()
            .contains("editable use"));
    }
    for bytes in [
        vec![],
        SYNTHETIC[..SYNTHETIC.len() / 2].to_vec(),
        vec![0; super::super::MAX_CONTENT + 1],
    ] {
        let (mut doc, _, _, program) = fixture();
        doc.get_object_mut(program)
            .unwrap()
            .as_stream_mut()
            .unwrap()
            .content = bytes;
        assert!(textedit::scan(&doc, 0).is_err());
    }
    for rights in [0_u16, 8, 0x100, 0x108] {
        let (mut doc, _, _, program) = fixture();
        let start = table_offset(b"OS/2") + 8;
        doc.get_object_mut(program)
            .unwrap()
            .as_stream_mut()
            .unwrap()
            .content[start..start + 2]
            .copy_from_slice(&rights.to_be_bytes());
        assert_eq!(textedit::scan(&doc, 0).unwrap().runs.len(), 2);
    }
}

#[test]
fn textedit_embedded_refuses_wrong_cmap_even_when_font_loads() {
    let (mut doc, _, _, program) = fixture();
    let start = table_offset(b"cmap");
    let stream = doc
        .get_object_mut(program)
        .unwrap()
        .as_stream_mut()
        .unwrap();
    // Change the Windows (3,1) encoding record to symbolic (3,0).
    let count =
        u16::from_be_bytes(stream.content[start + 2..start + 4].try_into().unwrap()) as usize;
    let mut changed = false;
    for record in stream.content[start + 4..start + 4 + count * 8].chunks_exact_mut(8) {
        if record[..4] == [0, 3, 0, 1] {
            record[3] = 0;
            changed = true;
        }
    }
    assert!(changed);
    assert!(Face::parse(&stream.content, 0).is_ok());
    assert!(textedit::scan(&doc, 0).is_err());
}

#[test]
fn textedit_embedded_does_not_treat_a_broken_space_as_blank() {
    let (mut doc, _, _, program) = fixture();
    let stream = doc
        .get_object_mut(program)
        .unwrap()
        .as_stream_mut()
        .unwrap();
    let face = Face::parse(&stream.content, 0).unwrap();
    assert_eq!(face.glyph_index(' '), Some(ttf_parser::GlyphId(1)));
    assert_eq!(
        face.tables().head.index_to_location_format,
        ttf_parser::head::IndexToLocationFormat::Short
    );
    assert!(face.glyph_bounding_box(ttf_parser::GlyphId(1)).is_none());
    // Equal loca offsets normally mean an empty glyph. Equal offsets beyond
    // the glyf table mean a malformed glyph, not proof that it paints nothing.
    let start = table_offset(b"loca") + 2;
    stream.content[start..start + 4].fill(0xff);
    let face = Face::parse(&stream.content, 0).unwrap();
    assert!(face.glyph_bounding_box(ttf_parser::GlyphId(1)).is_none());
    assert!(textedit::scan(&doc, 0)
        .unwrap_err()
        .contains("no validated glyph"));
}

#[test]
fn textedit_embedded_requires_unicode_cmaps_to_agree() {
    let read16 = |data: &[u8], at| u16::from_be_bytes(data[at..at + 2].try_into().unwrap());
    let start = table_offset(b"cmap");
    let raw = Face::parse(SYNTHETIC, 0)
        .unwrap()
        .raw_face()
        .table(Tag::from_bytes(b"cmap"))
        .unwrap();
    let mut cmap = raw.to_vec();
    assert_eq!(read16(&cmap, 2), 2);
    assert_eq!(read16(&cmap, 4), 0); // Unicode record, followed by Windows (3,1).
    let sub = u32::from_be_bytes(cmap[8..12].try_into().unwrap()) as usize;
    assert_eq!(read16(&cmap, sub), 4);
    let mut alternate = cmap[sub..sub + usize::from(read16(&cmap, sub + 2))].to_vec();
    let segments = usize::from(read16(&alternate, 6)) / 2;
    let segment = (0..segments)
        .find(|&i| {
            read16(&alternate, 14 + i * 2) >= 65
                && read16(&alternate, 16 + segments * 2 + i * 2) <= 65
        })
        .unwrap();
    let delta = 16 + segments * 4 + segment * 2;
    let shifted = read16(&alternate, delta).wrapping_add(1);
    alternate[delta..delta + 2].copy_from_slice(&shifted.to_be_bytes());
    let new_offset = cmap.len() as u32;
    cmap[8..12].copy_from_slice(&new_offset.to_be_bytes());
    cmap.extend(alternate);
    let mut bytes = SYNTHETIC.to_vec();
    let offset = bytes.len() as u32;
    // Move the complete cmap table to the end; the original stays unreachable.
    let records = usize::from(read16(&bytes, 4));
    for record in bytes[12..12 + records * 16].chunks_exact_mut(16) {
        if &record[..4] == b"cmap" {
            assert_eq!(
                u32::from_be_bytes(record[8..12].try_into().unwrap()) as usize,
                start
            );
            record[8..12].copy_from_slice(&offset.to_be_bytes());
            record[12..16].copy_from_slice(&(cmap.len() as u32).to_be_bytes());
        }
    }
    bytes.extend(cmap);
    let face = Face::parse(&bytes, 0).unwrap();
    let maps: Vec<_> = face.tables().cmap.unwrap().subtables.into_iter().collect();
    assert_eq!(maps.len(), 2);
    assert_ne!(maps[0].glyph_index(65), maps[1].glyph_index(65));
    let (mut doc, _, _, program) = fixture();
    doc.get_object_mut(program)
        .unwrap()
        .as_stream_mut()
        .unwrap()
        .content = bytes;
    assert!(textedit::scan(&doc, 0)
        .unwrap_err()
        .contains("character mapping"));
}

pub(super) fn custom_fixture() -> (Document, lopdf::ObjectId, lopdf::ObjectId) {
    let (mut doc, font, program) = mac_fixture(true);
    let face = Face::parse(SYNTHETIC, 0).unwrap();
    let alphabet = b"SYNTHEIC FR ODAB";
    let mut alphabet = alphabet.to_vec();
    // Unique byte -> glyph mapping, deliberately different from Unicode.
    let mut seen = std::collections::BTreeSet::new();
    alphabet.retain(|byte| seen.insert(*byte));
    let mut cmap = vec![0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 12, 0, 0, 1, 6, 0, 0];
    cmap.extend([0; 256]);
    let mut mappings = String::new();
    for (i, byte) in alphabet.iter().enumerate() {
        cmap[18 + i + 1] = face.glyph_index(char::from(*byte)).unwrap().0 as u8;
        mappings.push_str(&format!("<{:02X}> <{:04X}>\n", i + 1, byte));
    }
    let bytes = &mut doc
        .get_object_mut(program)
        .unwrap()
        .as_stream_mut()
        .unwrap()
        .content;
    let offset = bytes.len() as u32;
    let count = u16::from_be_bytes(bytes[4..6].try_into().unwrap()) as usize;
    for record in bytes[12..12 + 16 * count].chunks_exact_mut(16) {
        if &record[..4] == b"cmap" {
            record[8..12].copy_from_slice(&offset.to_be_bytes());
            record[12..16].copy_from_slice(&(cmap.len() as u32).to_be_bytes());
        }
    }
    bytes.extend(cmap);
    let map = format!("/CIDInit/ProcSet findresource begin 12 dict begin begincmap /CIDSystemInfo << /Registry (Adobe) /Ordering (UCS) /Supplement 0 >> def /CMapName /Adobe-Identity-UCS def /CMapType 2 def 1 begincodespacerange <00> <FF> endcodespacerange {} beginbfchar\n{mappings}endbfchar endcmap CMapName currentdict /CMap defineresource pop end end", alphabet.len());
    let map = doc.add_object(Stream::new(Dictionary::new(), map.into_bytes()));
    let descriptor = doc
        .get_dictionary(font)
        .unwrap()
        .get(b"FontDescriptor")
        .unwrap()
        .as_reference()
        .unwrap();
    doc.get_dictionary_mut(descriptor).unwrap().set("Flags", 4);
    let f = doc.get_dictionary_mut(font).unwrap();
    f.remove(b"Encoding");
    f.set("ToUnicode", map);
    f.set("FirstChar", 0);
    f.set("LastChar", alphabet.len() as i64);
    let mut widths = vec![Object::Integer(600); alphabet.len() + 1];
    widths[0] = Object::Integer(0);
    f.set("Widths", widths);
    for page in crate::pagetree::ordered_pages(&doc) {
        let mut content =
            lopdf::content::Content::decode_strict(&doc.get_page_content(page)).unwrap();
        for op in &mut content.operations {
            if op.operator == "Tj" {
                let bytes = op.operands[0]
                    .as_str()
                    .unwrap()
                    .iter()
                    .map(|b| (alphabet.iter().position(|v| v == b).unwrap() + 1) as u8)
                    .collect::<Vec<_>>();
                op.operands[0] = Object::string_literal(bytes);
            }
        }
        let id = doc.add_object(Stream::new(Dictionary::new(), content.encode().unwrap()));
        doc.get_dictionary_mut(page).unwrap().set("Contents", id);
    }
    (doc, font, program)
}

#[test]
fn textedit_symbolic_ranges_roundtrip_preserves_mapping_and_other_pages() {
    let (mut doc, font, _) = custom_fixture();
    let map = doc
        .get_dictionary(font)
        .unwrap()
        .get(b"ToUnicode")
        .unwrap()
        .as_reference()
        .unwrap();
    let source = doc.get_object_mut(map).unwrap().as_stream_mut().unwrap();
    // Same symbolic font, but Quartz-style scalar ranges. The last range
    // covers A and B; each earlier entry has an explicitly separate endpoint.
    source.content = b"/CIDInit /ProcSet findresource begin 12 dict begin begincmap
        /CIDSystemInfo << /Registry (Adobe) /Ordering (UCS) /Supplement 0 >> def
        /CMapName /Adobe-Identity-UCS def /CMapType 2 def
        1 begincodespacerange <00> <FF> endcodespacerange
        14 beginbfrange
        <01><01><0053>
        <02><02><0059>
        <03><03><004e>
        <04><04><0054>
        <05><05><0048>
        <06><06><0045>
        <07><07><0049>
        <08><08><0043>
        <09><09><0020>
        <0a><0a><0046>
        <0b><0b><0052>
        <0c><0c><004f>
        <0d><0d><0044>
        <0e><0f><0041>
        endbfrange
        endcmap CMapName currentdict /CMap defineresource pop end end"
        .to_vec();
    let before = doc.objects.clone();
    let runs = textedit::scan(&doc, 0).unwrap();
    assert_eq!(runs.runs[0].text, "SYNTHETIC FIRST");
    let other = textedit::scan(&doc, 1).unwrap();
    for replacement in ["AB", "EDITED FIRST"] {
        let mut edited = doc.clone();
        let update = change(&edited, replacement);
        textedit::write(&mut edited, &[update]).unwrap();
        assert_eq!(
            textedit::scan(&edited, 0).unwrap().runs[0].text,
            replacement
        );
        assert_eq!(textedit::scan(&edited, 0).unwrap().runs[1], runs.runs[1]);
        assert_eq!(textedit::scan(&edited, 1).unwrap().runs, other.runs);
        let page = crate::pagetree::ordered_pages(&edited)[0];
        let content =
            lopdf::content::Content::decode_strict(&edited.get_page_content(page)).unwrap();
        let bytes = content.operations[runs.runs[0].operator as usize].operands[0]
            .as_str()
            .unwrap();
        assert_eq!(
            &bytes[..2],
            if replacement == "AB" {
                &[14, 15]
            } else {
                &[6, 13]
            }
        );
        // Every old object is immutable; only the edited page gets a new stream.
        for (id, value) in &before {
            if *id != page {
                assert_eq!(edited.objects[id], *value, "changed object {id:?}");
            }
        }
    }
    let update = change(&doc, "Z");
    assert!(textedit::write(&mut doc, &[update])
        .unwrap_err()
        .contains("no validated glyph"));
    assert_eq!(doc.objects, before);
}

#[test]
fn textedit_symbolic_codes_round_trip_without_changing_font_resources() {
    let (mut doc, font, program) = custom_fixture();
    let before = doc.objects.clone();
    let runs = textedit::scan(&doc, 0).unwrap();
    assert_eq!(runs.runs[0].text, "SYNTHETIC FIRST");
    let update = change(&doc, "EDITED FIRST");
    textedit::write(&mut doc, &[update]).unwrap();
    assert_eq!(
        textedit::scan(&doc, 0).unwrap().runs[0].text,
        "EDITED FIRST"
    );
    assert_eq!(textedit::scan(&doc, 0).unwrap().runs[1], runs.runs[1]);
    assert_eq!(doc.objects[&font], before[&font]);
    assert_eq!(doc.objects[&program], before[&program]);
    let page = crate::pagetree::ordered_pages(&doc)[0];
    let ops = lopdf::content::Content::decode_strict(&doc.get_page_content(page)).unwrap();
    // Not ASCII: the first three codes are E, D, I in this synthetic mapping.
    let show = &ops.operations[runs.runs[0].operator as usize];
    assert_eq!(&show.operands[0].as_str().unwrap()[..3], &[6, 13, 7]);
    for absent in ["Z", "ä", "!"] {
        let state = doc.objects.clone();
        let edit = change(&doc, absent);
        assert!(textedit::write(&mut doc, &[edit])
            .unwrap_err()
            .contains("no validated glyph"));
        assert_eq!(doc.objects, state);
    }
}

#[test]
fn textedit_symbolic_codes_require_unambiguous_glyph_selection_and_widths() {
    for kind in 0..6 {
        let (mut doc, font, program) = custom_fixture();
        match kind {
            0 => {
                doc.get_dictionary_mut(font)
                    .unwrap()
                    .set("Encoding", "MacRomanEncoding");
            }
            1 => {
                let d = doc
                    .get_dictionary(font)
                    .unwrap()
                    .get(b"FontDescriptor")
                    .unwrap()
                    .as_reference()
                    .unwrap();
                doc.get_dictionary_mut(d).unwrap().set("Flags", 32);
            }
            2 => {
                doc.get_dictionary_mut(font)
                    .unwrap()
                    .get_mut(b"Widths")
                    .unwrap()
                    .as_array_mut()
                    .unwrap()[1] = Object::Integer(10);
            }
            3 => {
                doc.get_dictionary_mut(font).unwrap().remove(b"ToUnicode");
            }
            5 => {
                let bytes = &mut doc
                    .get_object_mut(program)
                    .unwrap()
                    .as_stream_mut()
                    .unwrap()
                    .content;
                let old = Face::parse(bytes, 0)
                    .unwrap()
                    .raw_face()
                    .table(Tag::from_bytes(b"cmap"))
                    .unwrap()
                    .to_vec();
                let mut duplicate =
                    vec![0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 20, 0, 1, 0, 0, 0, 0, 0, 20];
                duplicate.extend(&old[12..]);
                let offset = bytes.len() as u32;
                let count = u16::from_be_bytes(bytes[4..6].try_into().unwrap()) as usize;
                for record in bytes[12..12 + 16 * count].chunks_exact_mut(16) {
                    if &record[..4] == b"cmap" {
                        record[8..12].copy_from_slice(&offset.to_be_bytes());
                        record[12..16].copy_from_slice(&(duplicate.len() as u32).to_be_bytes());
                    }
                }
                bytes.extend(duplicate);
            }
            _ => {
                doc.get_object_mut(program)
                    .unwrap()
                    .as_stream_mut()
                    .unwrap()
                    .content[..4]
                    .copy_from_slice(&[0, 1, 0, 0]);
            }
        }
        assert!(textedit::scan(&doc, 0).is_err(), "accepted case {kind}");
    }
    let (mut doc, _, _) = custom_fixture();
    let before = doc.objects.clone();
    let edit = change(&doc, &"S".repeat(80));
    assert!(textedit::write(&mut doc, &[edit])
        .unwrap_err()
        .contains("original text advance"));
    assert_eq!(doc.objects, before);
}

#[test]
fn textedit_symbolic_codes_refuse_unmapped_and_oversized_runs() {
    for (bytes, reason) in [
        (vec![255], "unmapped font code"),
        (
            vec![1; textedit::MAX_TEXT + 1],
            "mapped text exceeds its limit",
        ),
    ] {
        let (mut doc, _, _) = custom_fixture();
        let page = crate::pagetree::ordered_pages(&doc)[0];
        let mut content =
            lopdf::content::Content::decode_strict(&doc.get_page_content(page)).unwrap();
        let show = content
            .operations
            .iter_mut()
            .find(|op| op.operator == "Tj")
            .unwrap();
        show.operands[0] = Object::string_literal(bytes);
        let stream = doc.add_object(Stream::new(Dictionary::new(), content.encode().unwrap()));
        doc.get_dictionary_mut(page)
            .unwrap()
            .set("Contents", stream);
        assert!(textedit::scan(&doc, 0).unwrap_err().contains(reason));
    }
}

#[test]
fn textedit_default_helvetica_maps_codes_and_widths() {
    let metrics = Metrics::helvetica_default();
    assert_eq!(metrics.decode(&[169, 193, 163, 251]).unwrap(), "'`£ß");
    assert_eq!(metrics.encode("'`£ß").unwrap(), vec![169, 193, 163, 251]);
    assert_eq!(
        metrics.advance("'`£ß", 1000.).unwrap(),
        191. + 333. + 556. + 611.
    );
    for code in [0, 31, 39, 96, 127, 160, 164, 174, 255] {
        assert!(metrics.decode(&[code]).is_err(), "accepted code {code}");
    }
    for text in ["Ä", "é", "’", "\u{a0}"] {
        assert!(metrics.encode(text).is_err(), "encoded {text}");
        assert!(metrics.advance(text, 12.).is_err(), "measured {text}");
    }
    assert!(metrics.decode(&vec![65; textedit::MAX_TEXT + 1]).is_err());
    let rows: Vec<_> = (0..=255_u8)
        .map(|code| {
            let text = metrics.decode(&[code]).ok();
            let width = text
                .as_ref()
                .map(|text| metrics.advance(text, 1000.).unwrap());
            let encoded = text.as_ref().map(|text| metrics.encode(text).unwrap());
            if text.is_some() {
                assert_eq!(encoded, Some(vec![code]));
            }
            serde_json::json!({"code":code,"text":text,"width":width,"encoded":encoded})
        })
        .collect();
    assert_eq!(
        rows.iter().filter(|row| !row["text"].is_null()).count(),
        117
    );
    if let Some(path) = std::env::var_os("TPDF_DEFAULT_ENCODING_PROBE") {
        std::fs::write(path, serde_json::to_vec_pretty(&rows).unwrap()).unwrap();
    }
}

fn default_helvetica_fixture() -> (Document, lopdf::ObjectId) {
    let mut doc = textedit::tests::fixture();
    let font = *doc
        .objects
        .iter()
        .find(|(_, o)| o.as_dict().is_ok_and(|d| d.get(b"BaseFont").is_ok()))
        .unwrap()
        .0;
    doc.get_dictionary_mut(font).unwrap().remove(b"Encoding");
    (doc, font)
}

#[test]
fn textedit_default_helvetica_preserves_resources_and_mapped_text() {
    let (mut doc, font) = default_helvetica_fixture();
    let page = crate::pagetree::ordered_pages(&doc)[0];
    let bytes=b"BT /F1 12 Tf 40 180 Td (SYNTHETIC \xa9 \xc1 \xa3 \xfb) Tj ET BT /F1 12 Tf 40 140 Td (SECOND) Tj ET";
    let stream = doc.add_object(Stream::new(Dictionary::new(), bytes.to_vec()));
    doc.get_dictionary_mut(page)
        .unwrap()
        .set("Contents", stream);
    let before = textedit::scan(&doc, 0).unwrap();
    assert_eq!(before.runs[0].text, "SYNTHETIC ' ` £ ß");
    let objects = doc.objects.clone();
    for replacement in ["Ä", "é", "SYNTHETIC FIRST FIRST FIRST"] {
        let edit = Change {
            layout: None,
            page: 0,
            revision: before.revision.clone(),
            operator: before.runs[0].operator,
            original: before.runs[0].text.clone(),
            replacement: replacement.into(),
        };
        assert!(textedit::write(&mut doc, &[edit]).is_err());
        assert_eq!(doc.objects, objects);
    }
    textedit::write(
        &mut doc,
        &[Change {
            layout: None,
            page: 0,
            revision: before.revision,
            operator: before.runs[0].operator,
            original: before.runs[0].text.clone(),
            replacement: "£ ' ` ß".into(),
        }],
    )
    .unwrap();
    let after = textedit::scan(&doc, 0).unwrap();
    assert_eq!(after.runs[0].text, "£ ' ` ß");
    assert_eq!(after.runs[1], before.runs[1]);
    for (id, object) in objects {
        if id != page {
            assert_eq!(doc.objects[&id], object);
        }
    }
    assert!(!doc.get_dictionary(font).unwrap().has(b"Encoding"));
    let content = lopdf::content::Content::decode_strict(&doc.get_page_content(page)).unwrap();
    assert_eq!(
        content.operations[before.runs[0].operator as usize].operands[0]
            .as_str()
            .unwrap(),
        b"\xa3 \xa9 \xc1 \xfb"
    );
}

#[test]
fn textedit_default_helvetica_refuses_explicit_or_custom_encodings() {
    for value in [
        Object::Null,
        Object::Name(b"StandardEncoding".to_vec()),
        Object::Name(b"MacRomanEncoding".to_vec()),
        Object::Dictionary(dictionary! {}),
        Object::Reference((9999, 0)),
    ] {
        let (mut doc, font) = default_helvetica_fixture();
        doc.get_dictionary_mut(font).unwrap().set("Encoding", value);
        assert!(textedit::scan(&doc, 0).is_err());
    }
    for key in [
        "ToUnicode",
        "Widths",
        "FontDescriptor",
        "FirstChar",
        "LastChar",
    ] {
        let (mut doc, font) = default_helvetica_fixture();
        doc.get_dictionary_mut(font).unwrap().set(key, Object::Null);
        assert!(textedit::scan(&doc, 0).is_err());
    }
    let (mut doc, font) = default_helvetica_fixture();
    assert!(textedit::scan(&doc, 0).is_ok());
    doc.get_dictionary_mut(font)
        .unwrap()
        .set("BaseFont", "Courier");
    assert!(textedit::scan(&doc, 0).is_err());
}

#[test]
fn textedit_symbolic_dash_roundtrip_keeps_original_font_codes_and_ink() {
    let (mut doc, font_id, _) = custom_fixture();
    let mapping = doc
        .get_dictionary(font_id)
        .unwrap()
        .get(b"ToUnicode")
        .unwrap()
        .as_reference()
        .unwrap();
    let stream = doc
        .get_object_mut(mapping)
        .unwrap()
        .as_stream_mut()
        .unwrap();
    let source = String::from_utf8(stream.content.clone()).unwrap();
    assert_eq!(source.matches("<0042>").count(), 1);
    stream.content = source.replace("<0042>", "<2013>").into_bytes();
    let metrics = embedded(&doc, doc.get_dictionary(font_id).unwrap()).unwrap();
    let encoded = metrics.encode("\u{2013}A").unwrap();
    assert_ne!(encoded[0], 0x96);
    assert_eq!(metrics.decode(&encoded).unwrap(), "\u{2013}A");
    let page = crate::pagetree::ordered_pages(&doc)[0];
    let mut body =
        lopdf::content::Content::decode_strict(b"1 Tc BT /F1 10 Tf 40 180 Td (REPLACE) Tj ET")
            .unwrap();
    body.operations[4].operands[0] = Object::string_literal(encoded);
    let content = doc.add_object(Stream::new(Dictionary::new(), body.encode().unwrap()));
    doc.get_dictionary_mut(page)
        .unwrap()
        .set("Contents", content);
    let before = doc.objects.clone();
    let runs = textedit::scan(&doc, 0).unwrap();
    assert_eq!(runs.runs[0].text, "\u{2013}A");
    assert_eq!(runs.runs[0].advance, 14.);
    let change = Change {
        layout: None,
        page: 0,
        revision: runs.revision,
        operator: runs.runs[0].operator,
        original: "\u{2013}A".into(),
        replacement: "A\u{2013}".into(),
    };
    textedit::write(&mut doc, &[change]).unwrap();
    assert_eq!(textedit::scan(&doc, 0).unwrap().runs[0].text, "A\u{2013}");
    let saved = lopdf::content::Content::decode_strict(&doc.get_page_content(page)).unwrap();
    assert_eq!(
        saved.operations[4].operands[0].as_str().unwrap(),
        metrics.encode("A\u{2013}").unwrap()
    );
    for (id, value) in before {
        if id != page {
            assert_eq!(doc.objects[&id], value);
        }
    }
    assert!(metrics.advance("B", 10.).is_err());
    assert!(Metrics::helvetica().advance("\u{2013}", 10.).is_err());
    assert!(Metrics::helvetica().encode("\u{2013}").is_err());
}

#[test]
fn textedit_word_spacing_uses_pdf_code_32_not_unicode_space() {
    // Exercise the actual encoding round trip: the same Unicode string has
    // different word spacing depending on which PDF bytes carry its glyphs.
    for (codes, bytes, expected, right) in [
        (None, vec![65, 32], 15.45, 11.45),
        (
            Some(Codes::Single({
                let mut codes = Box::new([None; 256]);
                codes[32] = Some(b'A');
                codes[1] = Some(b' ');
                codes
            })),
            vec![32, 1],
            15.45,
            13.45,
        ),
        (
            Some(Codes::Single({
                let mut codes = Box::new([None; 256]);
                codes[2] = Some(b'A');
                codes[1] = Some(b' ');
                codes
            })),
            vec![2, 1],
            13.45,
            11.45,
        ),
        (
            Some(Codes::Double([(32, b'A'), (256, b' ')].into())),
            vec![0, 32, 1, 0],
            13.45,
            11.45,
        ),
    ] {
        let mut metrics = Metrics::helvetica();
        metrics.codes = codes;
        assert_eq!(metrics.encode("A ").unwrap(), bytes);
        assert_eq!(metrics.decode(&bytes).unwrap(), "A ");
        let (advance, bounds) = metrics.spaced_layout("A ", 10., 2., 2.).unwrap();
        assert!(
            (advance - expected).abs() < 0.0001,
            "{advance} != {expected}"
        );
        assert!(
            (bounds[1] - right).abs() < 0.0001,
            "{} != {right}",
            bounds[1]
        );
    }
}

#[test]
fn textedit_large_word_spacing_keeps_original_code_semantics_and_finite_limits() {
    for (codes, spaced, ink) in [
        (None, true, 0.945),
        (
            Some(Codes::Single({
                let mut codes = Box::new([None; 256]);
                codes[32] = Some(b'A');
                codes[1] = Some(b' ');
                codes
            })),
            true,
            12.945,
        ),
        (
            Some(Codes::Single({
                let mut codes = Box::new([None; 256]);
                codes[2] = Some(b'A');
                codes[1] = Some(b' ');
                codes
            })),
            false,
            0.945,
        ),
        (
            Some(Codes::Double([(32, b'A'), (256, b' ')].into())),
            false,
            0.945,
        ),
    ] {
        let mut metrics = Metrics::helvetica();
        metrics.codes = codes;
        let bytes = metrics.encode("A ").unwrap();
        let (text, advance, bounds) = metrics.source_layout(&bytes, 1., 0., 12.).unwrap();
        assert_eq!(text, "A ");
        let expected = 0.945 + if spaced { 12. } else { 0. };
        assert!((advance - expected).abs() < 0.000001);
        assert!((bounds[1] - ink).abs() < 0.000001);
        assert_eq!(
            metrics.spaced_layout(&text, 1., 0., 12.).unwrap(),
            (advance, bounds)
        );
        for value in [f64::NAN, f64::INFINITY, f64::NEG_INFINITY, 1_000_001.] {
            // No affected code means the cursor cannot mask the value bound.
            assert!(metrics.spaced_layout("", 1., 0., value).is_err());
        }
        if spaced {
            assert!(metrics
                .spaced_layout("A ", 1., 0., 1_000_000.)
                .unwrap_err()
                .contains("advance exceeds"));
        }
    }
}

#[test]
fn textedit_named_unicode_requires_identity_and_agreeing_legacy_glyphs() {
    let (mut doc, font, _, program) = fixture();
    let face = Face::parse(SYNTHETIC, 0).unwrap();
    let raw = face.raw_face().table(Tag::from_bytes(b"cmap")).unwrap();
    assert_eq!(u16::from_be_bytes(raw[2..4].try_into().unwrap()), 2);
    // Retain both original Unicode records; append an independent Mac format 0.
    let mut cmap = vec![0, 0, 0, 3];
    for record in raw[4..20].chunks_exact(8) {
        cmap.extend(&record[..4]);
        cmap.extend((u32::from_be_bytes(record[4..8].try_into().unwrap()) + 8).to_be_bytes());
    }
    let mac_offset = raw.len() + 8;
    cmap.extend([0, 1, 0, 0]);
    cmap.extend((mac_offset as u32).to_be_bytes());
    cmap.extend(&raw[20..]);
    cmap.extend([0, 0, 1, 6, 0, 0]);
    for code in 0_u8..=255 {
        cmap.push(
            face.glyph_index(char::from(code))
                .map_or(0, |g| u8::try_from(g.0).unwrap()),
        );
    }
    let mut bytes = SYNTHETIC.to_vec();
    let offset = bytes.len();
    let count = u16::from_be_bytes(bytes[4..6].try_into().unwrap()) as usize;
    for record in bytes[12..12 + count * 16].chunks_exact_mut(16) {
        if &record[..4] == b"cmap" {
            record[8..12].copy_from_slice(&(offset as u32).to_be_bytes());
            record[12..16].copy_from_slice(&(cmap.len() as u32).to_be_bytes());
        }
    }
    bytes.extend(cmap);
    assert_eq!(
        Face::parse(&bytes, 0)
            .unwrap()
            .tables()
            .cmap
            .unwrap()
            .subtables
            .len(),
        3
    );
    doc.get_object_mut(program)
        .unwrap()
        .as_stream_mut()
        .unwrap()
        .content = bytes;
    assert!(textedit::scan(&doc, 0).is_err()); // No verified extraction map yet.
    let source = "/CIDInit /ProcSet findresource begin 12 dict begin begincmap /CIDSystemInfo << /Registry (Adobe) /Ordering (UCS) /Supplement 0 >> def /CMapName /Adobe-Identity-UCS def /CMapType 2 def 1 begincodespacerange <0000> <FFFF> endcodespacerange 1 beginbfrange <20> <59> <0020> endbfrange endcmap CMapName currentdict /CMap defineresource pop end end";
    let map = doc.add_object(Stream::new(Dictionary::new(), source.as_bytes().to_vec()));
    doc.get_dictionary_mut(font).unwrap().set("ToUnicode", map);
    let update = change(&doc, "FIRST");
    let original = doc.objects.clone();
    textedit::write(&mut doc, &[update]).unwrap();
    assert_eq!(textedit::scan(&doc, 0).unwrap().runs[0].text, "FIRST");
    for id in [font, program, map] {
        assert_eq!(doc.objects[&id], original[&id]);
    }
    for defect in 0..7 {
        let mut broken = doc.clone();
        match defect {
            0 => {
                broken
                    .get_object_mut(map)
                    .unwrap()
                    .as_stream_mut()
                    .unwrap()
                    .content = source.replace("<0020>", "<0021>").into_bytes();
            }
            1 => {
                broken
                    .get_object_mut(program)
                    .unwrap()
                    .as_stream_mut()
                    .unwrap()
                    .content[offset + mac_offset + 6 + 70] = 0;
            }
            2 => {
                broken
                    .get_dictionary_mut(font)
                    .unwrap()
                    .set("Encoding", "MacRomanEncoding");
            }
            3 => {
                broken
                    .get_dictionary_mut(font)
                    .unwrap()
                    .set("Encoding", "Unknown");
            }
            4 => {
                broken
                    .get_object_mut(map)
                    .unwrap()
                    .as_stream_mut()
                    .unwrap()
                    .content = source.replace("<59>", "<45>").into_bytes();
            }
            5 => {
                broken
                    .get_object_mut(map)
                    .unwrap()
                    .as_stream_mut()
                    .unwrap()
                    .content = source.replace("<20>", "<0020>").into_bytes();
            }
            _ => {
                let entries = (32_u8..=89)
                    .map(|code| {
                        let target = match code {
                            b'F' => b'I',
                            b'I' => b'F',
                            _ => code,
                        };
                        format!("<{code:02x}> <{target:04x}> ")
                    })
                    .collect::<String>();
                broken
                    .get_object_mut(map)
                    .unwrap()
                    .as_stream_mut()
                    .unwrap()
                    .content = source
                    .replace(
                        "1 beginbfrange <20> <59> <0020> endbfrange",
                        &format!("58 beginbfchar {entries} endbfchar"),
                    )
                    .into_bytes();
            }
        }
        assert!(
            textedit::scan(&broken, 0).is_err(),
            "accepted defect {defect}"
        );
        let objects = broken.objects.clone();
        assert!(textedit::write(&mut broken, &[change(&doc, "IN")]).is_err());
        assert_eq!(broken.objects, objects);
    }
}
