use super::*;
use crate::textedit::{self, Change};
use lopdf::{dictionary, Stream};

// Generated by testdata/make_textedit_embedded.py from original geometric
// outlines; MIT like this repository. Contains no installed font material.
const SYNTHETIC: &[u8] = include_bytes!("../synthetic.ttf");

fn fixture() -> (Document, lopdf::ObjectId, lopdf::ObjectId, lopdf::ObjectId) {
    let mut doc = textedit::tests::fixture();
    let program = doc.add_object(Stream::new(Dictionary::new(), SYNTHETIC.to_vec()));
    let descriptor = doc.add_object(dictionary! {
        "Type" => "FontDescriptor", "FontName" => "TPDFSynthetic", "Flags" => 32,
        "FontBBox" => vec![0.into(), 0.into(), 400.into(), 700.into()],
        "ItalicAngle" => 0, "Ascent" => 800, "Descent" => -200,
        "CapHeight" => 700, "StemV" => 100, "FontFile2" => program
    });
    let font = doc.add_object(dictionary! {
        "Type" => "Font", "Subtype" => "TrueType", "BaseFont" => "TPDFSynthetic",
        "Encoding" => "WinAnsiEncoding", "FirstChar" => 32, "LastChar" => 89,
        "Widths" => vec![Object::Integer(600); 58], "FontDescriptor" => descriptor
    });
    for page in crate::pagetree::ordered_pages(&doc) {
        doc.get_dictionary_mut(page).unwrap().set(
            "Resources",
            dictionary! { "Font" => dictionary! { "F1" => font } },
        );
    }
    (doc, font, descriptor, program)
}

fn change(doc: &Document, replacement: &str) -> Change {
    let runs = textedit::scan(doc, 0).unwrap();
    Change {
        page: 0,
        operator: runs.runs[0].operator,
        revision: runs.revision,
        original: runs.runs[0].text.clone(),
        replacement: replacement.into(),
    }
}

#[test]
fn textedit_embedded_subset_uses_own_widths_and_preserves_every_font_byte() {
    let (mut doc, font, descriptor, program) = fixture();
    let before = doc.objects.clone();
    let runs = textedit::scan(&doc, 0).unwrap();
    assert!((runs.runs[0].advance - 15. * 7.2).abs() < 1e-8);
    let update = change(&doc, "EDITED FIRST");
    textedit::write(&mut doc, &[update]).unwrap();
    assert_eq!(
        textedit::scan(&doc, 0).unwrap().runs[0].text,
        "EDITED FIRST"
    );
    assert_eq!(textedit::scan(&doc, 1).unwrap().runs, runs.runs);
    for id in [font, descriptor, program] {
        assert_eq!(doc.objects[&id], before[&id]);
    }
    // Export through the real serializer for independent readback when wanted.
    if let Some(path) = std::env::var_os("TPDF_EMBEDDED_PROBE") {
        doc.save(path).unwrap();
    }
}

#[test]
fn textedit_embedded_missing_glyph_and_own_width_overflow_leave_document_untouched() {
    for (replacement, reason) in [
        ("Z", "no validated glyph"),
        ("ä", "no validated glyph"),
        ("A A A A A A A AA", "exceed the original"),
    ] {
        let (mut doc, _, _, _) = fixture();
        let before = doc.objects.clone();
        let update = change(&doc, replacement);
        assert!(textedit::write(&mut doc, &[update])
            .unwrap_err()
            .contains(reason));
        assert_eq!(doc.objects, before);
    }
}

#[test]
fn textedit_graphics_restore_uses_the_active_font_for_replacement() {
    let (mut doc, font, _, _) = fixture();
    let page = crate::pagetree::ordered_pages(&doc)[0];
    // The raw name is not UTF-8. Neither the last Tf nor the lossy UI name
    // identifies the active embedded font after Q restores it.
    let mut fonts = dictionary! { "F2" => dictionary! {
        "Type" => "Font", "Subtype" => "Type1", "BaseFont" => "Helvetica", "Encoding" => "WinAnsiEncoding"
    }};
    fonts.set(b"F\xff".to_vec(), font);
    let stream = doc.add_object(Stream::new(
        Dictionary::new(),
        b"BT /F#ff 12 Tf ET q BT /F2 12 Tf ET Q BT 40 180 Td (AB) Tj ET".to_vec(),
    ));
    let page = doc.get_dictionary_mut(page).unwrap();
    page.set("Resources", dictionary! { "Font" => fonts });
    page.set("Contents", stream);
    let before = doc.objects.clone();
    let missing = change(&doc, "i");
    assert!(textedit::write(&mut doc, &[missing])
        .unwrap_err()
        .contains("no validated glyph"));
    assert_eq!(doc.objects, before);
    let valid = change(&doc, "BA");
    textedit::write(&mut doc, &[valid]).unwrap();
    assert_eq!(textedit::scan(&doc, 0).unwrap().runs[0].text, "BA");
}

#[test]
fn textedit_embedded_refuses_ambiguous_pdf_mappings_and_custom_metrics() {
    for (key, value) in [
        ("ToUnicode", Object::Null),
        ("Encoding", Object::Name(b"MacRomanEncoding".to_vec())),
        ("FirstChar", Object::Integer(-1)),
        ("LastChar", Object::Integer(256)),
        ("Widths", Object::Array(vec![600.into()])),
        ("Widths", Object::Array(vec![200.into(); 58])),
        ("Widths", Object::Array(vec![700.into(); 58])),
    ] {
        let (mut doc, font, _, _) = fixture();
        doc.get_dictionary_mut(font).unwrap().set(key, value);
        assert!(textedit::scan(&doc, 0).is_err(), "accepted {key}");
    }
    for flags in [0, 4, 36, 32 | 262144] {
        let (mut doc, _, descriptor, _) = fixture();
        doc.get_dictionary_mut(descriptor)
            .unwrap()
            .set("Flags", flags);
        assert!(textedit::scan(&doc, 0).is_err());
    }
}

fn table_offset(tag: &[u8; 4]) -> usize {
    let count = u16::from_be_bytes(SYNTHETIC[4..6].try_into().unwrap()) as usize;
    for record in SYNTHETIC[12..12 + 16 * count].chunks_exact(16) {
        if &record[..4] == tag {
            return u32::from_be_bytes(record[8..12].try_into().unwrap()) as usize;
        }
    }
    panic!("missing synthetic table");
}

#[test]
fn textedit_embedded_refuses_restricted_missing_or_corrupt_programs() {
    for rights in [1_u16, 2, 4, 12, 0x200, 0x8000] {
        let (mut doc, _, _, program) = fixture();
        let stream = doc
            .get_object_mut(program)
            .unwrap()
            .as_stream_mut()
            .unwrap();
        let start = table_offset(b"OS/2") + 8;
        stream.content[start..start + 2].copy_from_slice(&rights.to_be_bytes());
        assert!(textedit::scan(&doc, 0)
            .unwrap_err()
            .contains("editable use"));
    }
    for bytes in [
        vec![],
        SYNTHETIC[..SYNTHETIC.len() / 2].to_vec(),
        vec![0; super::super::MAX_CONTENT + 1],
    ] {
        let (mut doc, _, _, program) = fixture();
        doc.get_object_mut(program)
            .unwrap()
            .as_stream_mut()
            .unwrap()
            .content = bytes;
        assert!(textedit::scan(&doc, 0).is_err());
    }
    for rights in [0_u16, 8, 0x100, 0x108] {
        let (mut doc, _, _, program) = fixture();
        let start = table_offset(b"OS/2") + 8;
        doc.get_object_mut(program)
            .unwrap()
            .as_stream_mut()
            .unwrap()
            .content[start..start + 2]
            .copy_from_slice(&rights.to_be_bytes());
        assert_eq!(textedit::scan(&doc, 0).unwrap().runs.len(), 2);
    }
}

#[test]
fn textedit_embedded_refuses_wrong_cmap_even_when_font_loads() {
    let (mut doc, _, _, program) = fixture();
    let start = table_offset(b"cmap");
    let stream = doc
        .get_object_mut(program)
        .unwrap()
        .as_stream_mut()
        .unwrap();
    // Change the Windows (3,1) encoding record to symbolic (3,0).
    let count =
        u16::from_be_bytes(stream.content[start + 2..start + 4].try_into().unwrap()) as usize;
    let mut changed = false;
    for record in stream.content[start + 4..start + 4 + count * 8].chunks_exact_mut(8) {
        if record[..4] == [0, 3, 0, 1] {
            record[3] = 0;
            changed = true;
        }
    }
    assert!(changed);
    assert!(Face::parse(&stream.content, 0).is_ok());
    assert!(textedit::scan(&doc, 0).is_err());
}

#[test]
fn textedit_embedded_does_not_treat_a_broken_space_as_blank() {
    let (mut doc, _, _, program) = fixture();
    let stream = doc
        .get_object_mut(program)
        .unwrap()
        .as_stream_mut()
        .unwrap();
    let face = Face::parse(&stream.content, 0).unwrap();
    assert_eq!(face.glyph_index(' '), Some(ttf_parser::GlyphId(1)));
    assert_eq!(
        face.tables().head.index_to_location_format,
        ttf_parser::head::IndexToLocationFormat::Short
    );
    assert!(face.glyph_bounding_box(ttf_parser::GlyphId(1)).is_none());
    // Equal loca offsets normally mean an empty glyph. Equal offsets beyond
    // the glyf table mean a malformed glyph, not proof that it paints nothing.
    let start = table_offset(b"loca") + 2;
    stream.content[start..start + 4].fill(0xff);
    let face = Face::parse(&stream.content, 0).unwrap();
    assert!(face.glyph_bounding_box(ttf_parser::GlyphId(1)).is_none());
    assert!(textedit::scan(&doc, 0)
        .unwrap_err()
        .contains("no validated glyph"));
}

#[test]
fn textedit_embedded_requires_unicode_cmaps_to_agree() {
    let read16 = |data: &[u8], at| u16::from_be_bytes(data[at..at + 2].try_into().unwrap());
    let start = table_offset(b"cmap");
    let raw = Face::parse(SYNTHETIC, 0)
        .unwrap()
        .raw_face()
        .table(Tag::from_bytes(b"cmap"))
        .unwrap();
    let mut cmap = raw.to_vec();
    assert_eq!(read16(&cmap, 2), 2);
    assert_eq!(read16(&cmap, 4), 0); // Unicode record, followed by Windows (3,1).
    let sub = u32::from_be_bytes(cmap[8..12].try_into().unwrap()) as usize;
    assert_eq!(read16(&cmap, sub), 4);
    let mut alternate = cmap[sub..sub + usize::from(read16(&cmap, sub + 2))].to_vec();
    let segments = usize::from(read16(&alternate, 6)) / 2;
    let segment = (0..segments)
        .find(|&i| {
            read16(&alternate, 14 + i * 2) >= 65
                && read16(&alternate, 16 + segments * 2 + i * 2) <= 65
        })
        .unwrap();
    let delta = 16 + segments * 4 + segment * 2;
    let shifted = read16(&alternate, delta).wrapping_add(1);
    alternate[delta..delta + 2].copy_from_slice(&shifted.to_be_bytes());
    let new_offset = cmap.len() as u32;
    cmap[8..12].copy_from_slice(&new_offset.to_be_bytes());
    cmap.extend(alternate);
    let mut bytes = SYNTHETIC.to_vec();
    let offset = bytes.len() as u32;
    // Move the complete cmap table to the end; the original stays unreachable.
    let records = usize::from(read16(&bytes, 4));
    for record in bytes[12..12 + records * 16].chunks_exact_mut(16) {
        if &record[..4] == b"cmap" {
            assert_eq!(
                u32::from_be_bytes(record[8..12].try_into().unwrap()) as usize,
                start
            );
            record[8..12].copy_from_slice(&offset.to_be_bytes());
            record[12..16].copy_from_slice(&(cmap.len() as u32).to_be_bytes());
        }
    }
    bytes.extend(cmap);
    let face = Face::parse(&bytes, 0).unwrap();
    let maps: Vec<_> = face.tables().cmap.unwrap().subtables.into_iter().collect();
    assert_eq!(maps.len(), 2);
    assert_ne!(maps[0].glyph_index(65), maps[1].glyph_index(65));
    let (mut doc, _, _, program) = fixture();
    doc.get_object_mut(program)
        .unwrap()
        .as_stream_mut()
        .unwrap()
        .content = bytes;
    assert!(textedit::scan(&doc, 0)
        .unwrap_err()
        .contains("character mapping"));
}
