"""Generate src-tauri/src/textedit/fonts/standard.rs: advance widths of the
twelve Latin standard PDF fonts (ISO 32000-1 9.6.2.2) for printable WinAnsi
codes, the domain the text editor offers for standard Helvetica.

Two independent transcriptions of Adobe's Core 14 AFM metrics must agree on
every width, or nothing is written: ReportLab's table keyed by glyph name
(through its own WinAnsiEncoding) and pdfminer.six's keyed by character
(through Python's cp1252). A width either one mistyped makes them disagree.

Usage:
    uv run --with reportlab --with pdfminer.six python scripts/standard_font_widths.py
    uv run --with reportlab --with pdfminer.six python scripts/standard_font_widths.py --check
"""

import pathlib
import sys

from pdfminer.fontmetrics import FONT_METRICS
from reportlab.pdfbase import _fontdata

FONTS = [
    "Helvetica",
    "Helvetica-Bold",
    "Helvetica-Oblique",
    "Helvetica-BoldOblique",
    "Times-Roman",
    "Times-Bold",
    "Times-Italic",
    "Times-BoldItalic",
    "Courier",
    "Courier-Bold",
    "Courier-Oblique",
    "Courier-BoldOblique",
]
CODES = list(range(32, 127)) + list(range(160, 256))
OUT = pathlib.Path(__file__).resolve().parent.parent / "src-tauri/src/textedit/fonts/standard.rs"


def character(code):
    # WinAnsi 0xA0 and 0xAD are the space and hyphen glyphs (ISO 32000-1 D.2).
    return {0xA0: " ", 0xAD: "-"}.get(code, bytes([code]).decode("cp1252"))


def widths(font):
    names = _fontdata.encodings["WinAnsiEncoding"]
    by_glyph = _fontdata.widthsByFontGlyph[font]
    by_char = FONT_METRICS[font][1]
    result = []
    for code in CODES:
        glyph = {0xA0: "space", 0xAD: "hyphen"}.get(code, names[code])
        a = by_glyph[glyph]
        b = by_char[character(code)]
        if a != b:
            sys.exit(f"[FAIL] {font} code {code}: ReportLab {a}, pdfminer {b}")
        result.append(a)
    return result


def render():
    lines = [
        "//! Advance widths of the twelve Latin standard fonts, in 1/1000 em, for",
        "//! WinAnsi codes 32..=126 then 160..=255. Generated by",
        "//! `scripts/standard_font_widths.py` from two independent transcriptions of",
        "//! Adobe's Core 14 metrics that must agree; do not edit by hand.",
        "",
        "#[cfg(test)]",
        "mod tests;",
        "",
        "pub(super) const FONTS: [(&[u8], [u16; 191]); 12] = [",
    ]
    for font in FONTS:
        values = widths(font)
        lines.append(f'    (b"{font}", [')
        for start in range(0, len(values), 16):
            chunk = ", ".join(str(v) for v in values[start:start + 16])
            lines.append(f"        {chunk},")
        lines.append("    ]),")
    lines.append("];")
    return "\n".join(lines) + "\n"


def main():
    text = render()
    if "--check" in sys.argv:
        if OUT.read_text(encoding="utf-8") != text:
            sys.exit(f"[FAIL] {OUT} is stale; regenerate it")
        print(f"[OK] {OUT.name} matches both sources")
        return
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"[OK] wrote {OUT.name}: {len(FONTS)} fonts x {len(CODES)} codes")


main()
